### PR TITLE
Added Velas Mainnet

### PR DESCRIPTION
**Pull request by roman-tik**

### CODE REVIEW

**Comment by kuzdogan** [comment]
As stated in the [readme](https://github.com/ethereum/sourcify#adding-a-new-chain), can you please provide a test contract and metadata

**Comment by roman-tik** [comment]
Now it is.
https://github.com/ethereum-lists/chains/pull/484
@ogwurujohnson 
thx

**Comment by roman-tik** [comment]
is there anything else needed?

**Comment by kuzdogan** [comment]
We were able to look into this just now, sorry for the delay.

Are the files flattened? I see the metadata file has two sources with below hashes but the provided source has a contract and a library: 
```
sources: {
  "/Users/r/tmp/MetaCoin/contracts/ConvertLib.sol": {
    keccak256: "0x802fb99ec5d0aa49c37809e653d97c7d922951eaa400ff3ce81f665e77a38df7",
    urls: [
      "bzz-raw://c39ac4ab0ec6424a1fe00f06001482054cacda893e98501db20a44087bc559ae",
      "dweb:/ipfs/QmV5cuS3oyBBGY9SZNobTVnTYwAkWFtBQQdd1fE9zDerLP",
    ],
  },
  "/Users/r/tmp/MetaCoin/contracts/MetaCoin.sol": {
    keccak256: "0x7e34627c61102ed6c881136775155d892d8ea11f44891af74381211341c6b560",
    urls: [
      "bzz-raw://e1ab127705f908b0d89313501331b058cd5b4ecb6f26fb957efe55f07f07c12d",
      "dweb:/ipfs/Qmf6CDTRJrW8Tx9khPdBQv44isC2HGtcr5W4cw6DQmR8J7",
    ],
  },
}
```

Unlike Etherscan the source files are not to be flattened in Sourcify and each one described under sources is matched with the hash in the metadata. Can you please provide the files separately as they were compiled?

**Comment by kuzdogan** [comment]
The PR was automatically closed with the latest changes but the changes are not merged into our repository. I seem to have messed up a bit. Sorry for the confusion @roman-tik.

**Comment by roman-tik** [comment]
@kuzdogan ok, but do you still need the sources?

**Comment by roman-tik** [comment]
anyway, here are non flattened ones

[ConvertLib.sol.txt](https://github.com/ethereum/sourcify/files/7582263/ConvertLib.sol.txt)
[MetaCoin.sol.txt](https://github.com/ethereum/sourcify/files/7582265/MetaCoin.sol.txt)
[Migrations.sol.txt](https://github.com/ethereum/sourcify/files/7582266/Migrations.sol.txt)

**Comment by kuzdogan** [comment]
Merged with https://github.com/ethereum/sourcify/commit/26d401d944a0c3cd1c5cf86f29b9c704c99e092b

**Pull request merged**
