### PR TITLE
add: dogechain

### PR DESCRIPTION
**Pull request by oliviachef**
<sub>View in Huly <a href="https://app.huly.io/guest/w-kaanuzdogan-sourcify-65d30de0-75121c5c6c-fd615e?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWU1ODI3MThiNmVjZDA0ZDYyZDkxZjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2FhbnV6ZG9nYW4tc291cmNpZnktNjVkMzBkZTAtNzUxMjFjNWM2Yy1mZDYxNWUiLCJwcm9kdWN0SWQiOiIifQ.8ZY9KG8whHO06jWsHaQ6XHe9QE7CZa_ulPQTeuXrkWA">HI-702</a></sub>

### CODE REVIEW

**Comment by oliviachef** [comment]
> Hey @oliviachef, remember to add also the tests, thanks.

for any contract deployed on dogechain? (can i use previous ones or draft a new one?:)

**Comment by oliviachef** [comment]
hey, "1_storage.sol" is deployable, i tried to have immutable contracts done with most of the ways - wasnt same, so "i can deploy the mutable contract" and requesting to do the test run of immutable contract based on the uploaded file? let me know..thankie!:(

**Comment by oliviachef** [comment]
the mutable contract - metadata is good and dont need to worried about the problem seems to be while carrying out the WithImmutable.sol

i can deploy your mutable file and proceed with fixednumbers.sol as immutable?

**Comment by marcocastignoli** [comment]
thanks @oliviachef!

> i can deploy your mutable file and proceed with fixednumbers.sol as immutable? atleast would lower the "data" in any possible way.

yes you can! 👍

**Comment by marcocastignoli** [comment]
I just realized that the branch name is wrong. It must be: **add-chain-2000**. Also I just updated chains.json, so we can merge staging into the new branch. Thanks

**Comment by oliviachef** [comment]
> I just realized that the branch name is wrong. It must be: **add-chain-2000**. Also I just updated chains.json, so we can merge staging into the new branch. Thanks

are we good right now? or does it needs some more fixtures?:)

**Comment by marcocastignoli** [comment]
1. you have to create a new branch from your staging branch called add-chain-2000 and from that create a new pr.
2. also please remember to merge sourcify/staging  into your branch.

**Pull request closed without merging**
