### PR TITLE
Add Candle (version two)

### PR DESCRIPTION
**Pull request by samisbakedham**

### CODE REVIEW

**Comment by samisbakedham** [comment]
@kuzdogan the first two errors are unrelated to the chain we're trying to add, it seems to be due to matic mumbai. 
image

**Comment by kuzdogan** [comment]
Please follow the instructions more carefully https://docs.sourcify.dev/docs/chain-support/. 

You need to name the branch as `add-chain-{chainId}` and not target the master branch. And yes the matic error is unrelated so don't worry about that. You need to pass the test-new-chain test.

**Comment by samisbakedham** [comment]
> Please follow the instructions more carefully https://docs.sourcify.dev/docs/chain-support/. 
> 
> 
> 
> You need to name the branch as `add-chain-{chainId}` and not target the master branch. And yes the matic error is unrelated so don't worry about that. You need to pass the test-new-chain test.

Fixed, and passed the test-new-chain test!

**Comment by kuzdogan** [comment]
It is unfortunately not passing

**Comment by kuzdogan** [comment]
Turning off support for Candle as the chain seems to be stale

**Pull request closed without merging**
