### PR TITLE
Add Crystaleum 💎

### PR DESCRIPTION
**Pull request by billaure-crystaleum**
Tests are passing... 

{"name":"VerificationService","hostname":"LAPTOP-xxx","pid":39600,"level":30,"loc":"[MATCH]","chain":"103090","address":"0xE32195beC48Dca3adc89b95a6c2f36e68F1A89A0","msg":"Retrieving contract bytecode address","time":"2022-06-02T10:30:56.830Z","v":0}
{"name":"VerificationService","hostname":"LAPTOP-xxx","pid":39600,"level":30,"loc":"[GET_CREATION_DATA]","chain":"103090","contractAddress":"0xE32195beC48Dca3adc89b95a6c2f36e68F1A89A0","fetchAddress":"https://scan.crystaleum.org/address/0xE32195beC48Dca3adc89b95a6c2f36e68F1A89A0/transactions","msg":"Scraping block explorer","time":"2022-06-02T10:30:57.142Z","v":0}
    √ should verify a contract with immutables on Crystaleum (103090) (6760ms)

  2 passing (18s)

### CODE REVIEW

**Comment by kuzdogan** [comment]
Please don't modify the chains.json file manually.

**Comment by billaure-crystaleum** [comment]
Hi-yah @ohhkaneda copy that, have fixed my PR (reverted changes on chains.json)

PR 1213 of official chain list https://github.com/ethereum-lists/chains/pull/1213

**Comment by billaure-crystaleum** [comment]
@kuzdogan could we get this merged?

**Comment by kuzdogan** [comment]
Several things:
- Please set the target branch "staging" 
- Merge with or rebase onto latest changes in staging, we updates the chains.json. 
- It seems you deployed with the deploy scripts, so you are using the same contracts under `sources/shared`. Can you remove the folder `sources/103090` and instead use the files under `sources/shared` in `chain-tests.js`?

**Comment by billaure-crystaleum** [comment]
Hi yah @kuzdogan done

**Comment by kuzdogan** [comment]
I am sorry but this PR is messed up because you initially opened it against the master branch. 

I suggest opening a new one, again named properly as `add-chain-103090`, **branching out from staging** and **targeting staging** with just the changes you made to files `sourcify-chains.ts` and `chain-tests.js`. Please follow the instructions carefully in docs: https://docs.sourcify.dev/docs/chain-support/

**Comment by billaure-crystaleum** [comment]
Hi yah I resubmit PR #762

**Pull request closed without merging**
