### PR TITLE
add-chain-11111

### PR DESCRIPTION
**Pull request by dovbrand**
- Add Chain Support for WAGMI 
- Verify mutable contracts

### CODE REVIEW

**Comment by dovbrand** [comment]
@kuzdogan The chain that is causing the tests to fail is not the chain that I am trying to add

**Comment by kuzdogan** [comment]
Hello yes that is expected :+1:

**Comment by dovbrand** [comment]
How often does staging get merged to main?

**Comment by kuzdogan** [comment]
https://github.com/ethereum/sourcify/pull/734/

**Pull request merged**
