### PR TITLE
Add chain 420666

### PR DESCRIPTION
**Pull request by billaure-crystaleum**
Support for (KEK): kekchain
chain ID: 420666
network ID: 1

### CODE REVIEW

**Comment by billaure-crystaleum** [comment]
Hi-yah @kuzdogan please review the logs and report the error to us, we have confirmed the WithImmutables.sol verified manually and the logs of ci/circleci: node-v16 report ```Error: Status code does not exist: Cannot set headers after they are sent to the client```

To avoid clutter we closed old PR: https://github.com/ethereum/sourcify/pull/782

**Comment by billaure-crystaleum** [comment]
FireShot Capture 006 - test-new-chain (15734) - ethereum_sourcify - app circleci com

**Comment by billaure-crystaleum** [comment]
FireShot Capture 006 - test-new-chain (15734) - ethereum_sourcify - app circleci com

**Comment by billaure-crystaleum** [comment]
Look's like a bug on the ci/circleci: node-v16

```Error: Status code does not exist: Cannot set headers after they are sent to the client```

**Comment by billaure-crystaleum** [comment]
Contract WithImmutables.sol verified manually.

Proof: https://testnet-explorer.kekchain.com/address/0x0E8CebF16c5E8f4b9515C69c38d6dAFa54101b6e/contracts

**Comment by billaure-crystaleum** [comment]
FireShot Capture 004 - Remix - Ethereum IDE - remix ethereum org

**Comment by billaure-crystaleum** [comment]
Yeah seems error is on ci/circleci: node-v16 (not us)

FireShot Capture 007 - node-v16 (15733) - ethereum_sourcify - app circleci com
FireShot Capture 008 - node-v16 (15733) - ethereum_sourcify - app circleci com

**Comment by kuzdogan** [comment]
The `node v16` tests are currently irrelevant. Looks good 👍

**Comment by billaure-crystaleum** [comment]
Thanks, have a great weekend @kuzdogan 
Until next time mate.

**Pull request merged**
