### PR TITLE
add-chain-641230

### PR DESCRIPTION
**Pull request by BearNetwork-BRNKC**

### CODE REVIEW

**Comment by marcocastignoli** [comment]
Sorry to refuse again this PR. Can you use the right naming for the branch?

> 2. Fork the repository. Branch out from the staging branch with name add-chain-{chainId} (e.g. for Ethereum Mainnet add-chain-1). This branch name format is required for automated testing. For each chain please open a new PR for the tests to run (no multiple chains e.g. add-chain-1234-1235)

you have to use `add-chain-641230` in order to trigger the right CI

**Comment by marcocastignoli** [comment]
the branch name, not the PR name

**Comment by marcocastignoli** [comment]
sorry I need to close this since you are working on a fork. If you still want your network to be verified on Sourcify please follow this section in Sourcify's documentation: https://docs.sourcify.dev/docs/chain-support/

**Comment by BearNetwork-BRNKC** [comment]
Well, I plan to set up the instance directly, let's use the instance set up
by ourselves in the  Blockchain Explorer .

Because Bear Network Chain is going to become a public chain in Taiwan,
there is not much time to wait for third-party approval.













熊網區塊鏈-Bear Network-BRNKC
Web : https://bearnetwork.net
Doc : https://docs.bearnetwork.net
Linkedin : https://bit.ly/bearnetwork_net
<https://www.linkedin.com/company/bearnetwork>



Marco Castignoli ***@***.***> 於 2023年2月14日 週二 下午8:26寫道：

**Pull request closed without merging**
