### PR TITLE
Add Ozone Chain Mainnet

### PR DESCRIPTION
**Pull request by praddoskanna**
# Add New Chain 4000

## Checklist

- [x] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the `chains.json` file directly.
- [x] In `sourcify-chains.json` file
  - [x] I've set `supported: true`.
  - [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [x] `test-new-chain` test in Circle CI is passing.

### CODE REVIEW

**Comment by kuzdogan** [comment]
Turning off support for Ozone (4000) since the test contract 0x50A9B085260F80CFEb1Af8c7131980fC11238ccB does not exist on the chain anymore and the tests have been failing https://app.circleci.com/pipelines/github/ethereum/sourcify/8100/workflows/4eb4c06b-7d0b-4588-8eee-300ee6344edf/jobs/48257

**Comment by praddoskanna** [comment]
Hey @kuzdogan,

The Storage.sol contract has been redeployed.

New contract address: 0xf776d21c74BEde463E0Ac7aD7cF12a9b2c904D03
https://ozonescan.io/address/0xf776d21c74BEde463E0Ac7aD7cF12a9b2c904D03/contracts#address-tabs

Please re-enable support for Ozone (4000). Thanks!

**Comment by kuzdogan** [comment]
Why did the contract vanish in the first place? Are you resetting the chain? @praddoskanna

**Comment by praddoskanna** [comment]
> Why did the contract vanish in the first place? Are you resetting the chain? @praddoskanna

Hey @kuzdogan,

We had to reset our chain due to unforeseen circumstances.
Please restore support for the Ozone (4000) chain. Thanks!

**Pull request merged**
