### PR TITLE
feat: fraxtal mainnet and testnet

### PR DESCRIPTION
**Pull request by pegahcarter**
# Add New Chain 252, 2522

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request for a speedy review.

## Checklist

* [x] The branch is named as `add-chain-<chainId>`.
* [x] I haven't modified the `chains.json` file directly. (Waiting on https://github.com/ethereum-lists/chains/pull/4414 and https://github.com/ethereum-lists/chains/pull/4413)
* [ ] In `sourcify-chains.json` file
  * [x] I've set `supported: true`.
  * [ ] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why). - See PRs above
* [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
* [ ] `test-new-chain` test in Circle CI is passing.

Tests are still failing even though everything else is correct. I've also tried to update `chains.json` with the correct data found in the aforementioned PRs but it still fails.

<sub>View in Huly <a href="https://app.huly.io/guest/w-kaanuzdogan-sourcify-65d30de0-75121c5c6c-fd615e?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWU1N2VkOThiNmVjZDA0ZDYyZDJmMTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2FhbnV6ZG9nYW4tc291cmNpZnktNjVkMzBkZTAtNzUxMjFjNWM2Yy1mZDYxNWUiLCJwcm9kdWN0SWQiOiIifQ.Zl3hX1kGjl1jeYZ1bIfEGwtP6IG0ILiUyJTDaNz9Sek">HI-508</a></sub>

### CODE REVIEW

**Comment by marcocastignoli** [comment]
It seems like there are errors in the test-new-chain CI test. You can run the test locally by running

* `npm install`
* `npx lerna run build`
* `cd /services/server`
* `NEW_CHAIN_ID="252,2522" npm run test:chains`

**Comment by marcocastignoli** [comment]
Also, I noticed you changed the formatting of some files

**Comment by kuzdogan** [comment]
Hey sorry for the late response. I've fixed the issues with your files. The main thing was, the contract has `appendCBOR` false so it needs to be a partial match in tests. 

Just wondering, did you create the metadata manually or where did you get the metadata? It had some inconsistencies, specifically the path in `compilationTarget` (`Storage.sol`) wasn't matching the path under `sources` (`src/sources/Storage.sol`). Normally this has to always match if the metadata is generated by the compiler.

**Comment by pegahcarter** [comment]
@kuzdogan thanks for the fix!  I used the metadata generated from foundry within the `broadcast/` dir of my deployment.  So I'm not exactly sure how the inconsistencies show up?

**Comment by kuzdogan** [comment]
@pegahcarter You mean the `out/` folder? If the full file is available can you please share? 

The main inconsistency is between line 79 and 85 here:
image

https://github.com/ethereum/sourcify/pull/1281/commits/1d76b5fea4937462bbdeb89cd10020eb2be6cc88

**Comment by pegahcarter** [comment]
The inconsistency is probably from my `foundry.toml` then...

https://github.com/pegahcarter/sourcify-deploy/blob/master/out/Storage.sol/Storage.json

**Comment by pegahcarter** [comment]
Guess so.  Thanks for the fix :+1:

**Pull request merged**
