### PR TITLE
Sourcify chains json

### PR DESCRIPTION
**Pull request by kuzdogan**
Moves the chains list object in `sourcify-chains.ts` to a JSON called `sourcify-chains.json`. 

The new `sourcify-chains.json` file also contains the etherscanApi information, which eventually will be stored in the `SourcifyChain` instance. 

<details>
      <summary>
         Here's a full example of a chain entry:
      </summary>

```json
{
  // the chain id
  "1": {
    "sourcifyName": "Ethereum Mainnet", // required
    "supported": true, // required

    // optional
    "etherscanApi": {
      "apiURL": "https://api.etherscan.io",
      "apiKeyEnvName": "ETHERSCAN_API_KEY" // the name of the environment variable holding the api key
    },

    // optional
    "fetchContractCreationTxUsing": {
      // How to find the transaction hash that created the contract
      "etherscanApi": true, // if supported by the new etherscan api. Need to provide the etherscanApi config
      "blockscoutApi": {
        // blockscout v2 instances have an api endpoint for this
        "url": "https://gnosis.blockscout.com/"
      },
      "blockscoutScrape": {
        // scraping from old (server-side rendered) blockscout ui
        "url": "https://scan.pulsechain.com/"
      },
      "avalancheApi": true // avalanche subnets at glacier-api.avax.network have an api endpoint for this
    },

    // optional
    // Leave empty to use the default rpcs in chains.json i.e. chainid.network/chains.json
    "rpc": [
      "https://rpc.sepolia.io", // can be a simple url
      {
        "type": "FetchRequest", // ethers.js FetchRequest for header authenticated RPCs
        "url": "https://rpc.mainnet.ethpandaops.io",
        "headers": [
          {
            "headerName": "CF-Access-Client-Id",
            "headerEnvName": "CF_ACCESS_CLIENT_ID"
          },
          {
            "headerName": "CF-Access-Client-Secret",
            "headerEnvName": "CF_ACCESS_CLIENT_SECRET"
          }
        ]
      },
      {
        "type": "Alchemy", // Alchemy RPCs
        "url": "https://eth-mainnet.alchemyapi.io/v2/{ALCHEMY_API_KEY}",
        "apiKeyEnvName": "ALCHEMY_API_KEY"
      },
      {
        "type": "Infura", // Infura RPCs
        "url": "https://palm-mainnet.infura.io/v3/{INFURA_API_KEY}",
        "apiKeyEnvName": "INFURA_API_KEY"
      }
    ]
  }
}
```

</details>

This allows users to replace the JSON file directly or mounting an alternative file when running in a container, if they want to support different chains for their own instance.

TODO:

- [ ] Fix the tests
- [ ] Merge the docs: https://github.com/sourcifyeth/docs/pull/17

### CODE REVIEW

**Comment by marcocastignoli** [comment]
💯 but the sourcify-chains.json file should be configurable without git conflicts. We could do something like this:

image

and at deployment: `cp sourcify-chains.example.json sourcify-chains.json`

**Comment by kuzdogan** [comment]
> 💯 but the sourcify-chains.json file should be configurable without git conflicts. We could do something like this:
> 
> image
> and at deployment: `cp sourcify-chains.example.json sourcify-chains.json`

Not sure if I understand. Git conflicts for new chain PRs? How does the example solve that?

**Comment by kuzdogan** [comment]
Done, please have a final look @marcocastignoli

**Comment by kuzdogan** [comment]
Done. Can you have a final look? @marcocastignoli

**Review by marcocastignoli — APPROVED** [review]

**Pull request merged**
