### PR TITLE
Lists taraxa testnet and mainnet

### PR DESCRIPTION
**Pull request by VargaElod23**
# Add New Chain <chainId>

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request for a speedy review.

## Checklist

- [x] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the `chains.json` file directly.
- [x] In `sourcify-chains.json` file
  - [x] I've set `supported: true`.
  - [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [x] `test-new-chain` test in Circle CI is passing.

## Summary by CodeRabbit

- **New Features**
  - Added support for Taraxa Mainnet and Taraxa Testnet with configurations including RPC endpoints and API for fetching contract creation transactions.

- **Tests**
  - Added verification tests for contracts on Taraxa Mainnet and Taraxa Testnet.

### CODE REVIEW

**Comment by manuelwedler** [comment]
Hey there! Thanks for the PR. We were experimenting with Coderabbit lately, but it should actually not be running on the chain adding PRs. Please ignore these suggestions and remove your last commit. It is not necessary to have the chainId field there.

Could you please also remove the rpc fields? We are already getting these from the chains.json

**Comment by VargaElod23** [comment]
All done @manuelwedler

**Comment by manuelwedler** [comment]
Please also remove the chainId fields

**Comment by VargaElod23** [comment]
Oh, I thought I amended that, sorry, it slipped out somehow. Done now @manuelwedler

**Review by manuelwedler — APPROVED** [review]

**Comment by kuzdogan** [comment]
Is the given contract for the Taraxa Testnet (842) changed? Now the bytecode of `0x98edEa58C0500287B973348ec315f3d26D0e189A` is returning a different result and the test is failing. I can see this PR is from Jul 2 but the explorer shows this contract was deployed on Jul 26: https://testnet.explorer.taraxa.io/address/0x98edea58c0500287b973348ec315f3d26d0e189a Is this testnet being reset?

**Pull request merged**
