### PR TITLE
add: unpruned RPC to chain 7700 in chains.json

### PR DESCRIPTION
**Pull request by tkkwon1998**
- adding an unpruned canto node to chains.json

### CODE REVIEW

**Comment by marcocastignoli** [comment]
this should be updated on https://github.com/ethereum-lists/chains, not here

**Comment by tkkwon1998** [comment]
thanks for the quick response @marcocastignoli! 

How often does chains.json for sourcify update? Is it based on some type of release schedule? Our pr to https://github.com/ethereum-lists/chains was merged yesterday.

**Comment by marcocastignoli** [comment]
Yes we'll do it soon! Eary next week @kuzdogan

**Comment by kuzdogan** [comment]
We can do a quick release tomorrow https://github.com/ethereum/sourcify/pull/930 👍

**Comment by kuzdogan** [comment]
https://github.com/ethereum/sourcify/releases/tag/v1.2.2

**Pull request closed without merging**
