### PR TITLE
Add New Chain 6119 (SK)

### PR DESCRIPTION
**Pull request by dfenstermaker**
# Add New Chain <chainId>

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request.

## Checklist

- [x] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the [chains.json](../../src/chains.json) file directly.
- [x] In [sourcify-chains.ts](../../src/sourcify-chains.ts) file
  - [x] I've set `supported: true`.
  - [x] I've set `monitored: false`.
  - [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [ ] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [x] `test-new-chain` test in Circle CI is passing.

### CODE REVIEW

**Comment by kuzdogan** [comment]
Hello

It seems you didn't add a test. Can you please add a chain test?

**Comment by dfenstermaker** [comment]
Added the test and its failing but this is the right data

**Comment by kuzdogan** [comment]
The file you're adding is not the metadata but the hardhat artifact.

Also please remove the changes the the `server.port` and `console.log` statements.

**Comment by kuzdogan** [comment]
Rebased and tests passing 👍

**Pull request merged**
