### PR TITLE
Add Scroll Sepolia Testnet and Scroll Mainnet

### PR DESCRIPTION
**Pull request by unchase**
# Add New Chain <chainId>

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request for a speedy review.

## Checklist

- [x] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the `chains.json` file directly.
- [x] In `sourcify-chains.json` file
  - [x] I've set `supported: true`.
  - [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [x] `test-new-chain` test in Circle CI is passing.

image

### CODE REVIEW

**Comment by marcocastignoli** [comment]
We were doing the same thing 🤣  Did you actually deploy the shared/ contract on mainnet?

**Comment by marcocastignoli** [comment]
https://github.com/ethereum/sourcify/pull/1260

**Comment by unchase** [comment]
> We were doing the same thing 🤣 Did you deploy the shared/ contract on mainnet?

Yep, the Store contract

**Comment by marcocastignoli** [comment]
then we'll keep you PR, thanks!

**Comment by unchase** [comment]
@marcocastignoli So, When is this going to go into production? We're just about to get the contract deployment and verification in Scroll =)

**Comment by marcocastignoli** [comment]
There is a big new feature in staging, so I cannot tell you exactly when, hopefully next week

**Pull request merged**
