### PR TITLE
add: 7700 canto mainnet test contracts

### PR DESCRIPTION
**Pull request by jessepinkman9900**
- [Website](canto.io)
- [Twitter](https://twitter.com/cantopublic)
- Chain ID: 7700

__NOTE__: creating new PR as circle CI failed in #790

### CODE REVIEW

**Comment by jessepinkman9900** [comment]
@marcocastignoli Circle CI failed here as well. can you help me fix this issue?

**Comment by marcocastignoli** [comment]
I'm in contact with the CircleCI support, I'll let you know. Thanks

**Comment by marcocastignoli** [comment]
They say:
`Can you confirm that the user who created the forked PR is only following the original project in CircleCI, and not the fork?`

**Comment by jessepinkman9900** [comment]
@marcocastignoli im not too familiar w Circle CI. Does `following the original project in Circle CI` mean that I select `ethereum/sourcify` in the organisation list in the Circle CI app? Thank you for your help!

This is the error is see for the Circle CI pipeline on the app. How do i proceed?
Screen Shot 2022-09-14 at 9 16 27 PM

**Comment by marcocastignoli** [comment]
In the Projects page in CircleCI you have to follow sourcify and not your fork. (I believe :laughing: )

**Comment by marcocastignoli** [comment]
That is the error that I showed to the support team, the other solution could be to logout-login again in circleci

**Comment by jessepinkman9900** [comment]
@marcocastignoli 
1. tried logout-login - did not work :/
2. how do I follow `ethereum/sourcify` when I'm not a part of the organisation in Circle CI?

**Comment by kuzdogan** [comment]
Actually you wouldn't need to do anything like following if you just fork and open a PR but there seems to be something wrong with your (Github) account's CircleCI settings. Are you logging in with your Github in CircleCI. For everyone else this has been working without any problems.

**Comment by jessepinkman9900** [comment]
had to give circle ci access from the organisation that owns the fork. circle ci runs are functional now. will fix the issues w my test cases and push

**Comment by marcocastignoli** [comment]
Sorry if I couldn't help you more, I'm glad that you fixed the issue :)

Il sab 17 set 2022, 06:15 Srinivas Kota (Sai) ***@***.***> ha
scritto:

**Comment by jessepinkman9900** [comment]
@marcocastignoli your comments helped me find the solution. thank you for all the help!

**Comment by jessepinkman9900** [comment]
Thank you @kuzdogan

**Pull request merged**
