### PR TITLE
Update sourcify-chains.ts Add Bear Network Mainnet ID 641230

### PR DESCRIPTION
**Pull request by BearNetwork-BRNKC**

### CODE REVIEW

**Comment by marcocastignoli** [comment]
Hello, can you please provide also the tests? Please follow all the steps in this page, thanks. https://docs.sourcify.dev/docs/chain-support/

**Comment by BearNetwork-BRNKC** [comment]
Hello

[image: 圖片 002.png]











熊網區塊鏈-Bear Network-BRNKC
Web : https://bearnetwork.net
Doc : https://docs.bearnetwork.net
Linkedin : https://bit.ly/bearnetwork_net
<https://www.linkedin.com/company/bearnetwork>



Marco Castignoli ***@***.***> 於 2023年1月31日 週二 下午5:18寫道：

**Comment by marcocastignoli** [comment]
I cannot see the attached image

**Comment by BearNetwork-BRNKC** [comment]
[png](https://buildroyal.idv.tw/sourcify.png)

**Comment by BearNetwork-BRNKC** [comment]
This is an image

**Comment by BearNetwork-BRNKC** [comment]
> I cannot see the attached image

This is an image

**Comment by marcocastignoli** [comment]
By test I meant point 5. **Provide test contracts** of the documentation

**Comment by BearNetwork-BRNKC** [comment]
熊網區塊鏈-Bear Network-BRNKC
Web : https://bearnetwork.net
Doc : https://docs.bearnetwork.net
Linkedin : https://bit.ly/bearnetwork_net
<https://www.linkedin.com/company/bearnetwork>



Marco Castignoli ***@***.***> 於 2023年1月31日 週二 下午9:47寫道：

**Comment by BearNetwork-BRNKC** [comment]
Hello

My English is not very good, waste your precious time. terribly sorry.🙏











熊網區塊鏈-Bear Network-BRNKC
Web : https://bearnetwork.net
Doc : https://docs.bearnetwork.net
Linkedin : https://bit.ly/bearnetwork_net
<https://www.linkedin.com/company/bearnetwork>



Marco Castignoli ***@***.***> 於 2023年1月31日 週二 下午9:47寫道：

**Comment by marcocastignoli** [comment]
Don't worry @BearNetwork-BRNKC :slightly_smiling_face:

**Comment by BearNetwork-BRNKC** [comment]
> Don't worry @BearNetwork-BRNKC 🙂

I finally know what to do.

**Comment by BearNetwork-BRNKC** [comment]
I am currently trying

Pin the IPFS repository


QmcmCQX5FtvmjboLqEP3VbBYk6w2SX49nNdNdozAYGJ4TW

ipns://repo.sourcecify.dev/

19 GB ................................................😱😱😱











熊網區塊鏈-Bear Network-BRNKC
Web : https://bearnetwork.net
Doc : https://docs.bearnetwork.net
Linkedin : https://bit.ly/bearnetwork_net
<https://www.linkedin.com/company/bearnetwork>



Marco Castignoli ***@***.***> 於 2023年1月31日 週二 下午10:38寫道：

**Comment by marcocastignoli** [comment]
> I am currently trying Pin the IPFS repository QmcmCQX5FtvmjboLqEP3VbBYk6w2SX49nNdNdozAYGJ4TW ipns://repo.sourcecify.dev/ 19 GB

this is not necessary

**Pull request closed without merging**
