### PR TITLE
chore: add new chain OORT Mainnet

### PR DESCRIPTION
**Pull request by molecula451**
# Add New Chain <chainId>

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request for a speedy review.

## Checklist

- [x] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the `chains.json` file directly.
- [x] In `sourcify-chains.json` file
  - [x] I've set `supported: true`.
  - [ ] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [x] `test-new-chain` test in Circle CI is passing.

### CODE REVIEW

**Comment by molecula451** [comment]
@manuelwedler

**Review by manuelwedler — CHANGES_REQUESTED** [review]
Thanks for the PR! Could you please remove the rpc field from `sourcify-chains.json`? It is already included in `chains.json`

**Comment by molecula451** [comment]
> Thanks for the PR! Could you please remove the rpc field from `sourcify-chains-default.json`? It is already included in `chains.json`

You are right, thanks, fixed

**Review by manuelwedler — APPROVED** [review]
thanks!

**Pull request merged**
