### PR TITLE
add: dogechain.

### PR DESCRIPTION
**Pull request by oliviachef**

### CODE REVIEW

**Comment by oliviachef** [comment]
will this do?

**Comment by marcocastignoli** [comment]
yes, but the tests are failing: https://app.circleci.com/pipelines/github/ethereum/sourcify/4031/workflows/66be2b36-19aa-480f-b627-0871ba17c1b7/jobs/22062/parallel-runs/0/steps/0-104

**Comment by oliviachef** [comment]
> yes, but the tests are failing: https://app.circleci.com/pipelines/github/ethereum/sourcify/4031/workflows/66be2b36-19aa-480f-b627-0871ba17c1b7/jobs/22062/parallel-runs/0/steps/0-104

they are failing because of rpc errors? i made a pr to update the rpc list, would wait for them to accept it and retry!:)

**Comment by marcocastignoli** [comment]
@oliviachef you can merge from staging, I updated the chains.json

**Comment by oliviachef** [comment]
> @oliviachef you can merge from staging, I updated the chains.json

wew, thankie! - well, werent you off for the weekend? awesome, thankieeee!!

**Comment by kuzdogan** [comment]
Can you maybe open a new PR? The tests seem to be failing.

We've updated the Requesting Chain Support docs https://docs.sourcify.dev/docs/chain-support/ In summary, you now don't need to provide a contract with immutables.

**Pull request closed without merging**
