### PR TITLE
Palm network

### PR DESCRIPTION
**Pull request by miguel567**
Adding Palm Network (palm.io)

### CODE REVIEW

**Comment by skenaja** [comment]
Hi @ogwurujohnson did you get a chance to review this one? Thanks!

**Comment by ogwurujohnson** [comment]
@skenaja yes i did, can you provide me the exact metadata file for the `Greeter` contract and the address where it's deployed on both chains

**Comment by miguel567** [comment]
@ogwurujohnson 
Addresses are at:
test/testcontracts/PalmContract/mainnet-address.txt
test/testcontracts/PalmContract/testnet-address.txt


Metadata is: test/testcontracts/ERC20Standard/metadata.json

Let me know if you have any questions.

**Comment by mbaxter** [comment]
@ogwurujohnson - any update on this?

**Comment by miguel567** [comment]
@ogwurujohnson Fixed a couple of small conflicts. do you have an ETA for merging?

**Comment by ogwurujohnson** [comment]
@miguel567 in chain.json, palm network has no rpc url provided, can you add this, since we need it for verification. https://chainid.network/chains.json

**Comment by mbaxter** [comment]
PR open to add rpc urls here: https://github.com/ethereum-lists/chains/pull/832

**Comment by mbaxter** [comment]
@ogwurujohnson - if you need to access the Palm infura rpc api's, you can register to get access here: https://docs.palm.io/Get-Started/Connect/Mainnet/

**Comment by skenaja** [comment]
@ogwurujohnson - any update?

FYI, Palm Network RPCs are now available in the Infura Settings dashboard

image

**Comment by ogwurujohnson** [comment]
Sorry for the late response, taking a look at this plus others today.

**Comment by skenaja** [comment]
Hi @ogwurujohnson any blockers preventing this from being merged? Sorry for chasing, we have a lot of demand from our users on the Palm Network asking for this!

**Comment by kuzdogan** [comment]
What is the contract deployed at addresses `0xC1572CAadDcC2bCBC3F7779F08592f6b5EE4Eea4` mainnet and `0xead777460174dC843D4d3A5691E2416fF3eA2F64` testnet? 

I see you attached `Greeter.sol` but the metadata file has `ERC20Standard.sol`. When Sourcify compiles it get a vastly different bytecode than the deployed bytecode.
Deployed onchain bytecode:
```
0x608060405234801561001057600080fd5b50600436106100365760003560e01c8063a41368621461003b578063cfae321714610057575b600080fd5b61005560048036038101906100509190610445565b610075565b005b61005f61013c565b60405161006c91906104c7565b60405180910390f35b610122604051806060016040528060238152602001610707602391396000805461009e90610620565b80601f01602080910402602001604051908101604052809291908181526020018280546100ca90610620565b80156101175780601f106100ec57610100808354040283529160200191610117565b820191906000526020600020905b8154815290600101906020018083116100fa57829003601f168201915b50505050508361026a565b8060009080519060200190610138929190610332565b5050565b60606000805461014b90610620565b80601f016020809104026020016040519081016040528092919081815260200182805461017790610620565b80156101c45780601f10610199576101008083540402835291602001916101c4565b820191906000526020600020905b8154815290600101906020018083116101a757829003601f168201915b5050505050905090565b61026682826040516024016101e49291906104e9565b6040516020818303038152906040527f4b5c4277000000000000000000000000000000000000000000000000000000007bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19166020820180517bffffffffffffffffffffffffffffffffffffffffffffffffffffffff8381831617835250505050610309565b5050565b61030483838360405160240161028293929190610520565b6040516020818303038152906040527f2ced7cef000000000000000000000000000000000000000000000000000000007bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19166020820180517bffffffffffffffffffffffffffffffffffffffffffffffffffffffff8381831617835250505050610309565b505050565b60008151905060006a636f6e736f6c652e6c6f679050602083016000808483855afa5050505050565b82805461033e90610620565b90600052602060002090601f01602090048101928261036057600085556103a7565b82601f1061037957805160ff19168380011785556103a7565b828001600101855582156103a7579182015b828111156103a657825182559160200191906001019061038b565b5b5090506103b491906103b8565b5090565b5b808211156103d15760008160009055506001016103b9565b5090565b60006103e86103e384610591565b61056c565b905082815260208101848484011115610404576104036106e6565b5b61040f8482856105de565b509392505050565b600082601f83011261042c5761042b6106e1565b5b813561043c8482602086016103d5565b91505092915050565b60006020828403121561045b5761045a6106f0565b5b600082013567ffffffffffffffff811115610479576104786106eb565b5b61048584828501610417565b91505092915050565b6000610499826105c2565b6104a381856105cd565b93506104b38185602086016105ed565b6104bc816106f5565b840191505092915050565b600060208201905081810360008301526104e1818461048e565b905092915050565b60006040820190508181036000830152610503818561048e565b90508181036020830152610517818461048e565b90509392505050565b6000606082019050818103600083015261053a818661048e565b9050818103602083015261054e818561048e565b90508181036040830152610562818461048e565b9050949350505050565b6000610576610587565b90506105828282610652565b919050565b6000604051905090565b600067ffffffffffffffff8211156105ac576105ab6106b2565b5b6105b5826106f5565b9050602081019050919050565b600081519050919050565b600082825260208201905092915050565b82818337600083830152505050565b60005b8381101561060b5780820151818401526020810190506105f0565b8381111561061a576000848401525b50505050565b6000600282049050600182168061063857607f821691505b6020821081141561064c5761064b610683565b5b50919050565b61065b826106f5565b810181811067ffffffffffffffff8211171561067a576106796106b2565b5b80604052505050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052602260045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b600080fd5b600080fd5b600080fd5b600080fd5b6000601f19601f830116905091905056fe4368616e67696e67206772656574696e672066726f6d202725732720746f2027257327a264697066735822122054c7d53505216d5579da8e1f79710678e04e8ba5bf6eecea2d128e9dbfbf088464736f6c63430008060033
```

Recompiled bytecode:
```
0x608060405234801561001057600080fd5b506004361061009e5760003560e01c806354fd4d501161006657806354fd4d501461022457806370a08231146102a757806395d89b41146102ff578063a9059cbb14610382578063dd62ed3e146103d05761009e565b806306fdde03146100a3578063095ea7b31461012657806318160ddd1461017457806323b872dd14610192578063313ce56714610200575b600080fd5b6100ab610448565b6040518080602001828103825283818151815260200191508051906020019080838360005b838110156100eb5780820151818401526020810190506100d0565b50505050905090810190601f1680156101185780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b6101726004803603604081101561013c57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803590602001909291905050506104e6565b005b61017c6105d0565b6040518082815260200191505060405180910390f35b6101fe600480360360608110156101a857600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803590602001909291905050506105d6565b005b610208610959565b604051808260ff1660ff16815260200191505060405180910390f35b61022c61096c565b6040518080602001828103825283818151815260200191508051906020019080838360005b8381101561026c578082015181840152602081019050610251565b50505050905090810190601f1680156102995780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b6102e9600480360360208110156102bd57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610a0a565b6040518082815260200191505060405180910390f35b610307610a53565b6040518080602001828103825283818151815260200191508051906020019080838360005b8381101561034757808201518184015260208101905061032c565b50505050905090810190601f1680156103745780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b6103ce6004803603604081101561039857600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919080359060200190929190505050610af1565b005b610432600480360360408110156103e657600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610cef565b6040518082815260200191505060405180910390f35b60018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156104de5780601f106104b3576101008083540402835291602001916104de565b820191906000526020600020905b8154815290600101906020018083116104c157829003601f168201915b505050505081565b80600660003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055508173ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff167f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925836040518082815260200191505060405180910390a35050565b60005481565b80600560008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054101580156106a1575080600660008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205410155b80156106ad5750600081115b6106b657600080fd5b61070881600560008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054610d7690919063ffffffff16565b600560008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208190555061079d81600560008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054610d9590919063ffffffff16565b600560008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208190555061086f81600660008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054610d9590919063ffffffff16565b600660008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055508173ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef836040518082815260200191505060405180910390a3505050565b600260009054906101000a900460ff1681565b60048054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610a025780601f106109d757610100808354040283529160200191610a02565b820191906000526020600020905b8154815290600101906020018083116109e557829003601f168201915b505050505081565b6000600560008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020549050919050565b60038054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610ae95780601f10610abe57610100808354040283529160200191610ae9565b820191906000526020600020905b815481529060010190602001808311610acc57829003601f168201915b505050505081565b604060048101600036905014610b0357fe5b81600560003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205410158015610b525750600082115b610b5b57600080fd5b610bad82600560003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054610d9590919063ffffffff16565b600560003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002081905550610c4282600560008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054610d7690919063ffffffff16565b600560008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055508273ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef846040518082815260200191505060405180910390a3505050565b6000600660008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054905092915050565b600080828401905083811015610d8b57600080fd5b8091505092915050565b600082821115610da457600080fd5b60008284039050809150509291505056fea265627a7a7231582077c7ae4c1f3e74f2ff1d191a3899bceb2db26182af37798ed620197723cb622864736f6c63430005100032
```

Now we have an automatized chain support process outline in the [docs](https://docs.sourcify.dev/docs/chain-support/). It would be much easier if you can deploy the contracts with the `tests/chains/deployContracts.js` script via a private key and share the contract addresses. But you'll also need to handle the `{INFURA_KEY}` replacement. 

If you can send me just enough Palm ETH and Testnet ETH to `0xAA6042aa65eb93C6439cDaeBC27B3bd09c5DFe94` I can handle it, since you have been waiting for long.

**Comment by skenaja** [comment]
@kuzdogan I funded that account for you. Gas price between 1000-10,000 wei should be sufficient for deployments.  Many thanks for your offer to handle this for us.

**Comment by skenaja** [comment]
@kuzdogan looks like the `ERC20Standard.sol` included in the PR is just a linting change.  
The metadata file for `greeter.sol` is `test/testcontracts/PalmContract/6ec2e9bdf94dd7c680c3224c26ebd84a.json`

**Comment by kuzdogan** [comment]
@skenaja that's not the metadata but actually the hardhat output. It can contain the contract metadata but in this case, it doesn't. I suggest taking a look at https://docs.sourcify.dev/docs/metadata/ if you're not familiar with the contract metadata 

Anyway, added with https://github.com/ethereum/sourcify/commit/6d1f8882411b2715a93cd887842320c1a2b9308a and will be merged Monday if goes well.

**Comment by kuzdogan** [comment]
Merged to master https://github.com/ethereum/sourcify/commit/531cf31d66430a3d65a44d9a16bf2b7a1b86d79f

**Pull request closed without merging**
