### PR TITLE
Renamed and Enabled Kaia mainnet

### PR DESCRIPTION
**Pull request by praveen-kaia**
# Add New Chain 8217-1001

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request for a speedy review.

## Checklist

- [X] The branch is named as `add-chain-<chainId>`.
- [X] I haven't modified the `chains.json` file directly.
- [X] In `sourcify-chains.json` file
  - [X] I've set `supported: true`.
  - [X] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [X] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [ ] `test-new-chain` test in Circle CI is passing.

### CODE REVIEW

**Comment by kuzdogan** [comment]
Tests failing because of RPCs. Will check after #1768

**Comment by kuzdogan** [comment]
Tests are still failing.

**Comment by praveen-kaia** [comment]
HI @kuzdogan , 

I have corrected the RPC testnet url https://github.com/ethereum-lists/chains/pull/6336 . it got merged.
Should we wait for syncing the chain data to sourcify codebase ?

**Comment by praveen-kaia** [comment]
@kuzdogan , Fixed the issue. Can you please the PR now. Thanks for your time.

**Review by kuzdogan — APPROVED** [review]

**Comment by kuzdogan** [comment]
Thanks! Looking good

**Pull request merged**
