### PR TITLE
add xai mainnet and testnet

### PR DESCRIPTION
**Pull request by aodhgan**
# Add New Chain 660279 and 37714555429

## Checklist

- [x] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the `chains.json` file directly.
- [x] In `sourcify-chains.json` file
  - [x] I've set `supported: true`.
  - [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [x]  I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [x] `test-new-chain` test in Circle CI is passing.

### CODE REVIEW

**Comment by aodhgan** [comment]
hello @manuelwedler, the Xai chain(s) requested here have been merged into ethereum-lists in this PR (https://github.com/ethereum-lists/chains/pull/4990)

is there action required on my end to update the chains.json to get the circle ci tests passing?

**Comment by manuelwedler** [comment]
Hey @aodhgan ! We had to update our chains.json what we did today. Could you please rebase your changes on staging? Also please remove the rpcs

**Comment by kuzdogan** [comment]
@manuelwedler If the repository is forked on a personal account (not organization) maintainers can edit the PR and Github UI gives the option to merge/rebase, fyi

**Comment by aodhgan** [comment]
@manuelwedler thanks - removed the rpc endpoints

**Review by manuelwedler — APPROVED** [review]

**Pull request merged**
