### PR TITLE
Add chain 420666 (kekchain)

### PR DESCRIPTION
**Pull request by billaure-crystaleum**
Hi yah! Let's support for the one [kekchain](https://t.me/kekchain)

### CODE REVIEW

**Comment by billaure-crystaleum** [comment]
Look's ready for merge

**Comment by billaure-crystaleum** [comment]
Standing by for merge on our PR's to chainList! 

Submitted commits: 
https://github.com/ethereum-lists/chains/pull/1488
https://github.com/DefiLlama/chainlist/pull/118

**Comment by billaure-crystaleum** [comment]
Reinitialized tests. Still hitting "chain not supported" but the PR was merged in https://github.com/ethereum-lists/chains/pull/1488

**Comment by billaure-crystaleum** [comment]
Hi-yah! @kuzdogan could we get a second pair of eyes for a peer review in favor of this PR? 
I will fixup our PR for merge if needed. 

Thanks, Bill

**Comment by kuzdogan** [comment]
Updated the `chains.json`. Can you please rebase?

**Comment by jessepinkman9900** [comment]
@kuzdogan when will `chains.json` be updated again?

**Comment by kuzdogan** [comment]
It is updated on https://github.com/ethereum/sourcify/commit/f564112e4dc74a8f52a54fc2048e1ac54c8245cd you need to rebase this branch on staging to include the changes @jessepinkman9900

**Comment by jessepinkman9900** [comment]
thank you @kuzdogan

**Comment by billaure-crystaleum** [comment]
Hi-yah, will do

**Comment by billaure-crystaleum** [comment]
@kuzdogan hi-yah could you check on this PR? We deployed with deployContracts.js and seem to hit an issue.

**Comment by billaure-crystaleum** [comment]
Hmm seems bug.

**Comment by billaure-crystaleum** [comment]
Hmm seems maybe bug.
seeing this in ci/circleci: node-v16 logs
```failed, reason: getaddrinfo ENOTFOUND swarm-gateways.net```

**Comment by billaure-crystaleum** [comment]
We were able to verify the Proof.sol contract on the explorer directly, tests show it doesn't exist in contracts/ although we did upload it to 420666/immutable/Proof.sol

hmm

**Comment by billaure-crystaleum** [comment]
Immutables are loaded proper. 
FireShot Capture 004 - Remix - Ethereum IDE - remix ethereum org

**Comment by billaure-crystaleum** [comment]
Contract WithImmutables.sol verified manually.

Proof: https://testnet-explorer.kekchain.com/address/0x0E8CebF16c5E8f4b9515C69c38d6dAFa54101b6e/contracts

**Comment by billaure-crystaleum** [comment]
Look's like a bug on the ci/circleci: node-v16

```Error: Status code does not exist: Cannot set headers after they are sent to the client```

**Comment by billaure-crystaleum** [comment]
I will close this PR and reopen a fresh PR.

**Comment by billaure-crystaleum** [comment]
@kuzdogan please review the logs and report the error to us, we have confirmed the WithImmutables.sol verified manually and the logs of ci/circleci: node-v16 report ```Error: Status code does not exist: Cannot set headers after they are sent to the client```

Submitted a fresh PR: https://github.com/ethereum/sourcify/pull/788

**Pull request closed without merging**
