### PR TITLE
Fix etherscan instances test after server modularity refactoring

### PR DESCRIPTION
**Pull request by manuelwedler**
https://github.com/ethereum/sourcify/pull/1637 introduced changes which we didn't incorporate into the etherscan instances tests.

### CODE REVIEW

**Comment by manuelwedler** [comment]
added a tsc linting step to catch this problem earlier in the future.

**Review by kuzdogan — APPROVED** [review]

**Review by kuzdogan — CHANGES_REQUESTED** [review]
Tests failing

**Comment by manuelwedler** [comment]
Problem is that I build before linting, and some tools are not configured to ignore dist folder. Will fix it

**Comment by kuzdogan** [comment]
How do the changes now check the tests .ts files but don't build them? With the changes in `services/server/tsconfig.lint.json`?

**Review by kuzdogan — APPROVED** [review]

**Pull request merged**
