### PR TITLE
update-chain-7001 -- New RPC endpoints and test contracts for ZetaChain Athens3 Testnet

### PR DESCRIPTION
**Pull request by CharlieMc0**
I am updating the RPC endpoints, verifications contract, and explorer URLs for the Zetachain Athens network.

[A PR is pending in the ethereum-lists/chains repo](https://github.com/ethereum-lists/chains/pull/2955) to get the chain.json file updated - 

```
https://github.com/ethereum/sourcify/compare/ethereum:sourcify:staging...zeta-chain:update-chain-7001?template=add-new-chain.md&title=Add+New+Chain+%3CchainId%3E
```

### CODE REVIEW

**Comment by marcocastignoli** [comment]
Hello @CharlieMc0, please remove your edits to `src/chains.json`. We'll update the file once [your PR on ethereum-lists/chains](https://github.com/ethereum-lists/chains/pull/2955) is approved. Thanks.

**Comment by CharlieMc0** [comment]
Removed edits to chains.json and my PR on https://github.com/ethereum-lists/chains/pull/2955 has been merged.

**Comment by kuzdogan** [comment]
Why are you updating `services/core/build/sourcify-chains.js`? 

Just updated the `chains.json` on staging. Can you please merge or rebase and remove the changes at the above file?

**Comment by CharlieMc0** [comment]
I think i committed it on accident. I reverted it so now the only change is the verification contract. We regenesis'd the testnet so the contract had to be redeployed

**Comment by kuzdogan** [comment]
Ran the tests locally, merging.

**Comment by billyyang423** [comment]
Hello @kuzdogan I updated our RPC endpoints for chain 7001 in [this PR](https://github.com/ethereum-lists/chains/pull/4600) so we don't have verification support removed for this chain. If you could please help review it that would be great! Thank you! Let me know if there are any issues.

**Comment by kuzdogan** [comment]
Hey @billyyang423 I'm not a maintainer of that repo so it needs to be merged by a maintainer. Just lmk when it's done.

**Pull request merged**
