### PR TITLE
Fix typo in UI

### PR DESCRIPTION
**Pull request by franzihei**
typo was reported by QuickNode while working on a post about Sourcify :)

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Is it fine to directly merge this into master?

**Comment by franzihei** [comment]
Oh probably staging? I actually don't know how that works for the website.

**Comment by kuzdogan** [comment]
A typo fix should not cause trouble but might be better to push to staging first to not break the usual flow. I see even small changes being pushed to staging in the commit history.

**Comment by franzihei** [comment]
oh I think that messed some stuff up lol

**Comment by franzihei** [comment]
will close this and open with staging as a base

**Pull request closed without merging**
