### PR TITLE
Add chain 336 (Shiden - EVM)

### PR DESCRIPTION
**Pull request by rimrakhimov**

### CODE REVIEW

**Comment by kuzdogan** [comment]
Instead of an explicit `rpc` definition, it should be updated on [ethereum-lists/chains](https://github.com/ethereum-lists/chains) i.e. https://chainid.network/chains.json

**Comment by rimrakhimov** [comment]
@kuzdogan Updated in https://github.com/ethereum-lists/chains/pull/1784

**Comment by marcocastignoli** [comment]
hey @rimrakhimov, there was a problem in the tests, so I rebased this PR after the fix, now that test is passing, but it's still failing this test
```
1) Test Supported Chains
       should verify a contract with immutables on Shiden (EVM) (336):
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/circleci/source-verify/test/chains/chain-tests.js)
```

**Comment by rimrakhimov** [comment]
@marcocastignoli Hi, I believe the problem is that RPC endpoints specified in `chains.json` were not updated yet in Sourcify repository. They've been updated in https://github.com/ethereum-lists/chains/pull/1784 and merged into [ethereum-lists](https://github.com/ethereum-lists/chains) repository. But seems that `chains.json` has not yet picked up those changes

**Pull request merged**
