### PR TITLE
Hardhat metadata support

### PR DESCRIPTION
**Pull request by kuzdogan**

### CODE REVIEW

**Comment by NameItNow** [comment]
@kuzdogan Hi, any idea when this will be released to production?

**Comment by NameItNow** [comment]
The verification is working nicely on the staging website, but the repository is giving me bad gateway
https://repo.staging.sourcify.dev/contracts/full_match/5/0x2cc3502646b30d49f9d0F6213618b1501dF1Fd90/

**Comment by kuzdogan** [comment]
Thanks for the heads-up! Fixed it before pushing to production, thanks to you. Was a nasty bug.

It is planned to be released on monday #nodeployfridays :slightly_smiling_face:

**Comment by kuzdogan** [comment]
Merged with https://github.com/ethereum/sourcify/pull/594

**Comment by NameItNow** [comment]
> Merged with #594

Amazing news Imma be able to integrate sourcify on my app now 💯

**Pull request merged**
