### PR TITLE
Add chain 10243 (Arthera Testnet)

### PR DESCRIPTION
**Pull request by bertux**
# Add New Chain 10243

Thanks for reviewing our pull request to add a new support in Sourcify.

We have followed the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

We checked the following items before submitting our pull request.

## Checklist

- [x] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the [chains.json](../../src/chains.json) file directly.
- [x] In [sourcify-chains.ts](../../src/sourcify-chains.ts) file
  - [x] I've set `supported: true`.
  - [x] I've set `monitored: false`.
  - [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [x] `test-new-chain` test in Circle CI is passing.

### CODE REVIEW

**Comment by kuzdogan** [comment]
Hi is the testnet reset? The given test contract is not there anymore `0xa456Ad3DEe140dcC91655ff45ef3103C460201D0` The tests have been failing two weeks in a row and the chain will be deprecated.

**Comment by bertux** [comment]
Yes @kuzdogan the testnet has been reset but I was able to use Sourcify for it this morning so I will try to redeploy the same contract from the same wallet and the same nonce to get it deployed at the same address.
If I can't get the same address I will make a Pull Request to update the test contract address.

**Comment by kuzdogan** [comment]
@bertux great thanks. If the testnet will be reset recueringly then it would be nice to have either the same contract or the address replaced

**Comment by bertux** [comment]
The testnet has no other reset expected, I am deploying the test contract on the new testnet and I will create a new PR to replace the address. I will link the PR here when it's ready.

**Comment by bertux** [comment]
`Contract deployed at 0xE115Ef16e46bbF46591170D712140eC553C43553 on the chain Arthera Testnet (10243)`

**Comment by bertux** [comment]
@kuzdogan PR #1280 waiting for review to solve the failing CI test on Arthera Testnet.

**Comment by kuzdogan** [comment]
Turning off support for Arthera (10243) since the RPC https://rpc-test.arthera.net/ seem to be dysfunctional and the tests have been failing: https://app.circleci.com/pipelines/github/ethereum/sourcify/8100/workflows/4eb4c06b-7d0b-4588-8eee-300ee6344edf/jobs/48257

**Pull request merged**
