### PR TITLE
add-chain-13381

### PR DESCRIPTION
**Pull request by Fluffynorth**
add phoenix to sourcify-chains-default, already supported in playground.

# Add New Chain <13381>

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request for a speedy review.

## Checklist

* [x] The branch is named as `add-chain-<13381>`.
* [x] I haven't modified the `chains.json` file directly.
* [x] In `sourcify-chains.json` file
  * [x] I've set `supported: true`.
  * [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
* [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
* [ ] `test-new-chain` test in Circle CI is passing.

<sub>View in Huly <a href="https://huly.app/guest/w-kaanuzdogan-sourcify-65d30de0-75121c5c6c-fd615e?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWVhZTM2MDBhOTI5MzQ1M2YyMTQ2ZWYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2FhbnV6ZG9nYW4tc291cmNpZnktNjVkMzBkZTAtNzUxMjFjNWM2Yy1mZDYxNWUiLCJwcm9kdWN0SWQiOiIifQ.64g6vX5lUMpqyqRC5DJyeMc3rp8jsQvfRY4vLsOT6SQ">HI-1256</a></sub>

### CODE REVIEW

**Comment by Fluffynorth** [comment]
I need assistance I keep getting errors when trying to deploy test tokens keeps saying missing module dist/test/chain

**Comment by kuzdogan** [comment]
@Fluffynorth Are you building the project? `dist` is a build output folder

**Comment by Fluffynorth** [comment]
Yes, but after following the steps I make it to test token deployment and when trying to deploy I get the error missing module dist no module found for  dist/test/chains/ which is not the path either

**Comment by Fluffynorth** [comment]
@kuzdogan is there a video tutorial or reach out to to assist me with this?

**Comment by kuzdogan** [comment]
It seems you are not building the project. Are you running `npx lerna run build`? That's why the `dist/` folder can't be found. 

If you don't want to deploy using this method, you can also try option b that uses Thirdweb

**Pull request closed without merging**
