### PR TITLE
Add chain 534 - fixed

### PR DESCRIPTION
**Pull request by samisbakedham**
# **Passed Tests**
#

## **_1_Storage.sol_** ##

Screenshot 2022-05-12 034825
image

@kuzdogan the first two errors are unrelated to the chain we're trying to add, it seems to be due to matic mumbai. 
image

Updated the PR to a new branch named "add-chain-534" as requested and specified in the docs.

### CODE REVIEW

**Comment by samisbakedham** [comment]
> Please stop spamming the repo with new pull requests.
> 
> I see you deployed the contract but it is a partial match, so you probably didn't provide the exact same contract. Use the `deployContracts.js` script to deploy the exact same contracts or if you are using Remix check the metadata hash as outlined in the docs.
> 
> Finally don't open another PR unless you confirm the tests pass locally. You can run the tests with `NEW_CHAIN_ID={chainId} npx mocha test/chains/chain-tests.js --exit`.

Finally got it working! Thank you

**Comment by samisbakedham** [comment]
carbon (1)

**Comment by DLmwnStRMyHZeZ5XzExx83DmMS7BqdqUvt** [comment]
- [ ]

**Comment by samisbakedham** [comment]
> - [ ] 

?

**Comment by samisbakedham** [comment]
Hi, how do I request a review? Thank you

**Pull request merged**
