### PR TITLE
Taiko L3 chainId 167006

### PR DESCRIPTION
**Pull request by MarcusWentz**
# Add New Chain <chainId>

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request.

## Checklist

- [x] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the [chains.json](../../src/chains.json) file directly.
- [x] In [sourcify-chains.ts](../../src/sourcify-chains.ts) file
  - [x] I've set `supported: true`.
  - [x] I've set `monitored: false`.
  - [ ] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [ ] `test-new-chain` test in Circle CI is passing.

### CODE REVIEW

**Comment by MarcusWentz** [comment]
Test seems to be failing since file 
```
src/chains.json
```
hasn't synced with the new chain added to chainlist yet added here:
https://github.com/ethereum-lists/chains/pull/3198

**Comment by kuzdogan** [comment]
We are using a static `chains.json` file. Just updated the file https://github.com/ethereum/sourcify/commit/7f337c8ce3df0c8a76244b7a8e3095ccdeeb12d5. Can you please rebase or merge from staging?

**Comment by MarcusWentz** [comment]
In the failed build at link
https://app.circleci.com/pipelines/github/ethereum/sourcify/4430/workflows/7bc8d0be-1f49-4c85-a98c-fe6c6b600b52/jobs/24559
I see the following error
```
2023-07-24T13:42:03.132Z [warn]: IPFS_API not set, IPFS MFS will not be updated

AssertionError [ERR_ASSERTION]: You must provide an 'issuerBaseURL', an 'issuer' and 'jwksUri' or an 'issuer' and 'secret'
    at jwtVerifier (/home/circleci/source-verify/node_modules/express-oauth2-jwt-bearer/dist/index.js:264:12)
    at auth (/home/circleci/source-verify/node_modules/express-oauth2-jwt-bearer/dist/index.js:399:23)
    at Object.<anonymous> (/home/circleci/source-verify/dist/server/controllers/verification/verification.common.js:277:57)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/circleci/source-verify/dist/server/controllers/verification/session-state/session-state.handlers.js:4:31)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/circleci/source-verify/dist/server/controllers/verification/session-state/session-state.routes.js:5:34)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/circleci/source-verify/dist/server/routes.js:9:48)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/circleci/source-verify/dist/server/server.js:33:34)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/circleci/source-verify/test/chains/chain-tests.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireOrImport (/home/circleci/source-verify/node_modules/mocha/lib/esm-utils.js:15:12)
    at Object.exports.loadFilesAsync (/home/circleci/source-verify/node_modules/mocha/lib/esm-utils.js:28:26)
    at Mocha.loadFilesAsync (/home/circleci/source-verify/node_modules/mocha/lib/mocha.js:386:19)
    at singleRun (/home/circleci/source-verify/node_modules/mocha/lib/cli/run-helpers.js:149:15)
    at exports.runMocha (/home/circleci/source-verify/node_modules/mocha/lib/cli/run-helpers.js:186:11)
    at Object.exports.handler (/home/circleci/source-verify/node_modules/mocha/lib/cli/run.js:319:11)
    at /home/circleci/source-verify/node_modules/mocha/node_modules/yargs/lib/command.js:241:49

Exited with code exit status 1
```

**Comment by kuzdogan** [comment]
It seems this is related to https://github.com/ethereum/sourcify/pull/1090 can you please check @marcocastignoli ?

I suspect this is because the secret env variables are not available for external PRs

**Comment by marcocastignoli** [comment]
> I suspect this is because the secret env variables are not available for external PRs

This could definitely be the reason, I'll check.

**Comment by kuzdogan** [comment]
@MarcusWentz Initially the tests were failing because of our changes but now I see the contract is only partially verified. Did you deploy them with the script or with the thirdweb dashboard as explained? https://docs.sourcify.dev/docs/chain-support/

**Comment by MarcusWentz** [comment]
> @MarcusWentz Initially the tests were failing because of our changes but now I see the contract is only partially verified i.e. the metadata hash parts don't match. Did you deploy them with the script or with the thirdweb dashboard as explained? https://docs.sourcify.dev/docs/chain-support/

Sorry I just saw this. I see the pull request is merged with test-new-chain passing. I do not recall how I deployed the contract.
Will this cause issues verifying other contracts on this network? If so I can deploy the contract again with 
https://docs.sourcify.dev/docs/chain-support/

**Comment by kuzdogan** [comment]
No worries. Just added a parameter to cover the cases when the match is "partial". It should be fine 👍

**Pull request merged**
