### PR TITLE
Add support for Optimistic Kovan network

### LINKED ISSUE #352: Support for Optimism
Optimism network has launched and it is quite popular. Unfortunately, adding support for this L2 network is not straight forward as with most networks where we just have to add a new RPC URL.
Optimism is not EVM compatible, it uses a slightly modified version called OVM. For that reason, we would have to use a modified [solc](https://github.com/ethereum-optimism/solc-js) compiler for those verifications.

### PR DESCRIPTION
**Pull request by elenadimitrova**
Adds optimistic kovan to the supported networks.

### CODE REVIEW

**Comment by ligi** [comment]
Does the switch of optimism from OVM to EVM already happen? If this is not fully done we should not merge this PR

**Comment by kuzdogan** [comment]
Thanks for the PR Elena. As far as we understood Optimism is currenly using a [Solidity fork](https://github.com/ethereum-optimism/solidity) to compile contracts which [leaves out](https://community.optimism.io/docs/protocol/evm-comparison.html#replaced-opcodes) some opcodes. So it is not fully EVM compatible yet. In that case, the outputs of the standard Solidity compiler won't be matching the deployed bytecodes.

**Comment by elenadimitrova** [comment]
The switch to EVM is happening in a few days scheduled as:
Kovan - Oct 14
Mainnet - Oct 28

**Comment by ligi** [comment]
thanks for the info @elenadimitrova 
IMHO you should split the PR into main-net and testnet when there are different dates for the migration.
Also if I understood correctly you will recompile all contracts in the process. Any chance you can preserve the metadata? This way we could have all contracts before the merge verified,

**Comment by kuzdogan** [comment]
@elenadimitrova are you referring to the Optimism contracts on the Ethereum mainnet? It is possible to verify those before the merge (and we'd love to!). For the contracts on the Optimism network, we'd need to merge the PR as Sourcify needs to know from which chain and address to get the deployed byteCode and will compare it with the compiled byteCode.

**Comment by kuzdogan** [comment]
Great :clap: As stated [here](https://github.com/ethereum/sourcify#adding-a-new-chain), can you please provide a deployed contract, source code, and metadata so that we can test?

**Comment by chriseth** [comment]
.. or mabye just the source code and metadata for *all* the contracts? :)

**Comment by kuzdogan** [comment]
@elenadimitrova are the source & address & metadata of the newly deployed contracts on the testnet available? We'd love to verify them and add them to our repository.

I guess the mainnet migration is postponed to Nov 11.

**Comment by elenadimitrova** [comment]
@kuzdogan I have the source and metadata of the 8064 verified contracts on kovan. Where do you want them for testing?

**Comment by kuzdogan** [comment]
@elenadimitrova Great! How would it be the most convenient? Drive, Dropbox etc. all fine.

**Comment by ligi** [comment]
IPFS ;-)

**Comment by elenadimitrova** [comment]
Uploaded the `sourcify_optimistic-kovan` folder recursively here `QmdxW18bwSgpF11SAUocTD3RqPFa7R2L4hdeF6PzMqVDbm` This covers 8,064 contracts on kovan where there's an input and output json for each that is basically the contract object used as the solc compile input and respectively the output from compilation. Contract source is in the input, metadata in the output.

**Comment by kuzdogan** [comment]
None of us was able to view the data beyond `QmdxW18bwSgpF11SAUocTD3RqPFa7R2L4hdeF6PzMqVDbm` which shows `inputs` and `outputs` folders `QmPzTZTBpLwyLG5PUs3Cb4fNK3Jd4cECjLjctC5V9SY8wL` and `QmVxFQUJL6831CAvG3c5PpcH61aanQ3NTMPaa4qNX6a8j7` respectively. I.e. we cant open/get `QmPzTZTBpLwyLG5PUs3Cb4fNK3Jd4cECjLjctC5V9SY8wL` and `QmVxFQUJL6831CAvG3c5PpcH61aanQ3NTMPaa4qNX6a8j7`. Also doesn't work on the gateway:
https://ipfs.io/ipfs/QmPzTZTBpLwyLG5PUs3Cb4fNK3Jd4cECjLjctC5V9SY8wL?filename=inputs
https://ipfs.io/ipfs/QmVxFQUJL6831CAvG3c5PpcH61aanQ3NTMPaa4qNX6a8j7?filename=outputs

**Comment by elenadimitrova** [comment]
Uploaded temporarily to the cloud, see if you can read https://console.cloud.google.com/storage/browser/optimism-dev-uploads

**Comment by kuzdogan** [comment]
Parsed and tested individual files. Seems to work. Will test on staging, then will submit to Sourcify in bulk.

**Comment by kuzdogan** [comment]
@elenadimitrova Unfortunately many contracts seem to not have metadata in their output or the hashes don't match. In general I noticed two patterns for not being able to verify:

### 1. Can't verify because metadata is missing
These files don't have a `metadata` field in their output .json and their `sourceCode` field in input json is not a Solidity string but an object of sources:
```json
{{
  "language": "Solidity",
  "sources": {
    "Medianizer.sol": {
      "content": "// SPDX-License-Identifier: MIT\npragma solidity 0.6.12;\n\ni..."
    },
    "Median.sol": {
      "content": "// SPDX-License-Identifier: MIT\npragma solidity ^0.6.0..."
    },
    ...
    "SignedSafeMath.sol": {
      "content": "..."
    }
  },
  ...
}}
```
Also note the double brackets. We can actually parse these source files but in this error pattern, the metadata file is missing.

An example contract: `0x2f443c586d6de957919e9724ad6591967b85bc2f`

### 2. Source code hash does not match the metadata & can't fetch from IPFS
For example `0x45fa33e5020d0b5425b8f9fbb8ca0d08d7732361`

metadata
```json
{
  "compiler":{"version":"0.5.16+commit.9c3226ce"},
  "language":"Solidity",
  ...
  "sources": {
    "file": {
      "keccak256": "0xf34b4f5757a3dfa26d70c66604810bcae67219c0261b9da60af319de14c6604c",
      "urls": [
        "bzz-raw://26412c79bee1584c772658b6f084651eee24138c0093203eb14b1c7714ff0217",
        "dweb:/ipfs/QmezFmY9nMNYa6BqXs4nxDj8CGPquurGDxPcb9iPCL3hBr"
      ]
    }
  },
  "version": 1
}
```

The provided source code does not match keccak256 `0xf34b4f5757a3dfa26d70c66604810bcae67219c0261b9da60af319de14c6604c` and can't fetch `/ipfs/QmezFmY9nMNYa6BqXs4nxDj8CGPquurGDxPcb9iPCL3hBr`. We also try some whitespace variations but no match was found. All contracts of these case are Synthetix contracts with some ASCII art so I suspect this might be the issue.

Finally all matches have the sources in metadata in such format:
```json
{
  "compiler": { "version": "0.5.16+commit.9c3226ce" },
  "language": "Solidity",
  ...
  "sources": {
    "file": {
      "keccak256": "0xb355d0f536c3af950f2080ff6b51b4b16188dc3a7d132e886125a31c703e7f6e",
      "urls": [
        "bzz-raw://7b35689820e97ef65679ebb366c3cf7e429958e38aa99e6cfa0b018e611b14a1",
        "dweb:/ipfs/QmVGY8ZBQJWnW6D5SwiEUhXFARKSVztfvrhnkAMw2FC4jm"
      ]
    }
  },
}
```
Where "file" should be the relative source path like in the first example. This way the source code gets saved to `/contracts/full_match/69/0x00023Ba2513B1E475e9344FFe68DDC0a26917DC5/sources/file` without a `.sol` extension. 


If it is not possible to fix these in the testnet contract, can you consider these points for the mainnet contracts?

**Comment by kuzdogan** [comment]
Verification numbers locally
```
Perfect Match: 5311
Partial Match: 0
Unverified: 2753
```

Here are the lists of verified and unverified contracts:
[perfect.json](https://drive.google.com/file/d/1hyV906UFFs72IH13dcE7zrvSsakb53MH/view?usp=sharing)
[unverified.json](https://drive.google.com/file/d/1-sPamufC2RFsYAzYJUSKkrKddmRHn-ot/view?usp=sharing)

**Comment by kuzdogan** [comment]
I was able to partially verify Case 2: recompiled with the given compiler settings. Now I have a new metadata file and the keccak256 of the source matches the source file given. But the metadata hash of the onchain bytecode does not match recompiled bytecode.

**Comment by kuzdogan** [comment]
Also partially verified Case 1. But assuming the `sourceCode` field was the standard-json-input for the compiler, those contracts were compiled with the option 
```
    "metadata": {
      "bytecodeHash": "none"
    },
```
so no metadata hash was concatenated to the onchain bytecode, only the Solidity version.

**Pull request merged**
