### PR TITLE
Add New Chains Stratis 105105 205205

### PR DESCRIPTION
**Pull request by zeptin**
# Add New Chain 105105, 205205

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request for a speedy review.

## Checklist

- [x] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the `chains.json` file directly.
- [x] In `sourcify-chains.json` file
  - [x] I've set `supported: true`.
  - [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [ ] `test-new-chain` test in Circle CI is passing.

### CODE REVIEW

**Comment by manuelwedler** [comment]
Thanks for the PR! We just introduced TypeScript in our tests 3 hours ago. For that reason, your changes are conflicting. Could you make your changes again to latest `staging`?

**Comment by zeptin** [comment]
@manuelwedler the `test-new-chain` test seems to be failing due to something that looks unrelated to this PR, unless I am missing some config somewhere

**Comment by manuelwedler** [comment]
Yes, that error is expected. Looks fine now :)

**Review by manuelwedler — APPROVED** [review]

**Comment by kuzdogan** [comment]
We are turning off support for Auroria (205205) as the test contract 0x317306CE2b9CE1C8f419bfB2E480b4f000FB6B09. does not seem to exist anymore

**Comment by zeptin** [comment]
@kuzdogan Thanks for bringing this to our attention, we restarted our testnet and this contract didn't get re-deployed yet. I will open a PR shortly with the new address, if you could amend #2056 accordingly

**Pull request merged**
