### PR TITLE
Add Crab mainnet and Pangolin testnet

### PR DESCRIPTION
**Pull request by hujw77**
* test contract: test/chains/sources/shared/1_Storage.sol
* address 
  - pangolin testnet: https://pangolin.subscan.io/address/0x7de04a7596958D44baB52F4e5D0c9e79cB16ef8B
  - crab mainnet: https://crab.subscan.io/account/0xE0E78187F01E026bdD0bd901e5Ae2e10C022366D
* metadata: test/chains/sources/shared/1_Storage.metadata.json

### CODE REVIEW

**Comment by ogwurujohnson** [comment]
The url provided for crab mainnet points to pangolin testnet explorer

**Comment by hujw77** [comment]
> The url provided for crab mainnet points to pangolin testnet explorer, can you confirm and change this?

Thanks. I have changed the crab link.

**Comment by kuzdogan** [comment]
The RPC does not seem to work for both Crab and Pangolin. See: 
```
curl --location --request POST "http://pangolin-rpc.darwinia.network" \
--header 'Content-Type: application/json' \
--data-raw '{
  "jsonrpc": "2.0",
  "method": "eth_getCode",
  "params": [
    "0x8809f9b3ACEF1dA309f49b5Ab97A4C0faA64E6Ae",
    "0x2"
  ],
  "id": 1
}'
```

```
curl --location --request POST "http://crab-rpc.darwinia.network" \
--header 'Content-Type: application/json' \
--data-raw '{
  "jsonrpc": "2.0",
  "method": "eth_getCode",
  "params": [
    "0x22e272AE62661d94940F6F0a48309bcFEa4C5ee1",
    "0x2"
  ],
  "id": 1
}'
```

**Comment by kuzdogan** [comment]
Also please follow the added Chain Support Request docs: https://docs.sourcify.dev/docs/chain-support/

**Comment by hujw77** [comment]
> The RPC does not seem to work for both Crab and Pangolin.
> 
> I am getting the following response from the RPCs below: `Used HTTP Method is not allowed. POST or OPTIONS is required`
> 
> You can try with
> 
> ```
> curl --location --request POST "http://pangolin-rpc.darwinia.network" \
> --header 'Content-Type: application/json' \
> --data-raw '{
>   "jsonrpc": "2.0",
>   "method": "eth_getCode",
>   "params": [
>     "0x8809f9b3ACEF1dA309f49b5Ab97A4C0faA64E6Ae",
>     "0x2"
>   ],
>   "id": 1
> }'
> ```
> 
>  ```
> curl --location --request POST "http://crab-rpc.darwinia.network" \
> --header 'Content-Type: application/json' \
> --data-raw '{
>   "jsonrpc": "2.0",
>   "method": "eth_getCode",
>   "params": [
>     "0x22e272AE62661d94940F6F0a48309bcFEa4C5ee1",
>     "0x2"
>   ],
>   "id": 1
> }'
> ```

Please try this, I replace `http` to `https` and `0x2` to `latest`
```
curl --location --request POST "https://pangolin-rpc.darwinia.network" \
      --header 'Content-Type: application/json' \
      --data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_getCode",
    "params": [
      "0x8809f9b3ACEF1dA309f49b5Ab97A4C0faA64E6Ae",
      "latest"
    ],
    "id": 1
  }'
```
```
curl --location --request POST "https://crab-rpc.darwinia.network" \
      --header 'Content-Type: application/json' \
      --data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_getCode",
    "params": [
      "0x22e272AE62661d94940F6F0a48309bcFEa4C5ee1",
      "latest"
    ],
    "id": 1
  }'
```

**Comment by kuzdogan** [comment]
In this case, the rpc's in the [https://chainid.network/chains.json](https://chainid.network/chains.json) [GitHub: ethereum-lists/chains](https://github.com/ethereum-lists/chains) need to be updated as the rpc URLs are retrieved from there. Plus you'd want other users to easily add your chain via https://chainlist.org/ etc.

**Comment by hujw77** [comment]
> In this case, the rpc's in the https://chainid.network/chains.json (GitHub: [ethereum-lists/chains](https://github.com/ethereum-lists/chains)) need to be updated as the rpc URLs are retrieved from there. Plus you'd want other users to easily add your chain via https://chainlist.org/ etc.

I'll update rpc URLs, thanks for the suggestion.

**Comment by kuzdogan** [comment]
I see the RPC is fixed but I am getting a partial match when verifying. It seems the metadata provided above is different than the metadata of the deployed contract. Can you please check?

For faster processing, I'd suggest deploying the test contracts with the `deployContract.js` described in https://docs.sourcify.dev/docs/chain-support/

**Comment by hujw77** [comment]
> I see the RPC is fixed but I am getting a partial match when verifying. It seems the metadata provided above is different than the metadata of the deployed contract. Can you please check?
> 
> For faster processing, I'd suggest deploying the test contracts with the `deployContract.js` described in https://docs.sourcify.dev/docs/chain-support/

Thank you, but I run the script in trouble.
So use remix to deploy the `1_Storage.sol` contract, and  it's metadata ipfs cid matches to `ipfs://QmSffyjwZxAWUYaAiE25YPpKYyBegQKCBnnBK3tknDSgJ5`

* test contract: test/chains/sources/shared/1_Storage.sol
* address 
  - pangolin testnet: https://pangolin.subscan.io/address/0x7de04a7596958D44baB52F4e5D0c9e79cB16ef8B
  - crab mainnet: https://crab.subscan.io/account/0xE0E78187F01E026bdD0bd901e5Ae2e10C022366D
* metadata: test/chains/sources/shared/1_Storage.metadata.json

**Comment by kuzdogan** [comment]
Added to staging with https://github.com/ethereum/sourcify/commit/5b39a75ecc5f6fe403bf818a8b1e9a3973b1a51b can be seen at https://staging.sourcify.dev.

**Comment by hujw77** [comment]
> Added to staging with [5b39a75](https://github.com/ethereum/sourcify/commit/5b39a75ecc5f6fe403bf818a8b1e9a3973b1a51b) can be seen at https://staging.sourcify.dev.
> 
> Also do you remember what was the problem with the script? Trying to improve the experience @hujw77

I think the reason is I have not done the step 4.Install and build the project [Running Locally](https://docs.sourcify.dev/docs/run-locally/)
Because it is too heavy for me to run it.

**Comment by kuzdogan** [comment]
Turning off support for Pangolin testnet as the tests have been failing and there are no contracts on Sourcify.

**Pull request closed without merging**
