### PR TITLE
Add Elysium Mainnet chain 

### PR DESCRIPTION
**Pull request by aqeelVaival**
# Add New Chain 1339

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request.

## Checklist

- [ ✅ ] The branch is named as `add-chain-1339`.
- [ ✅ ] I haven't modified the [chains.json](../../src/chains.json) file directly.
- [ ✅ ] In [sourcify-chains.ts](../../src/sourcify-chains.ts) file
  - [✅  ] I've set `supported: true`.
  - [ ✅ ] I've set `monitored: false`.
  - [✅  ] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [ ✅ ] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [ ✅ ] `test-new-chain` test in Circle CI is passing.

### CODE REVIEW

**Comment by kuzdogan** [comment]
I believe you have deployed the `1_Storage` contract at `0x20563837F7423465699D7675BCB82f886a761c25` as I can see in the test but I also see you add an additional large [LERC20-role.sol](https://github.com/ethereum/sourcify/pull/1055/files#diff-65c979c93ef10dbe5e9226cfc69b338d983029961ba05475c5bf0349383e4527). Can you remove the added `.sol` file?

**Comment by aqeelVaival** [comment]
@kuzdogan why test cases have being failing?

**Comment by aqeelVaival** [comment]
@kuzdogan please let me know once you are available, kindly help to get it merge

**Comment by kuzdogan** [comment]
Apparently `lerna` pushed a new version `v7` which removes the `bootstrap` command we were using to install our submodules. Now the CI flows install the specific version before calling.

Can you please rebase or merge from staging?

**Pull request merged**
