### PR TITLE
add boba l2 rinkeby and mainnet

### PR DESCRIPTION
**Pull request by InoMurko**
**Boba Rinkeby:**
Contract: https://blockexplorer.rinkeby.boba.network/address/0xf71904bD3DCD3141BAF74AFD8F17281e207defe6/transactions
Source:
```
// SPDX-License-Identifier: LGPL-3.0-only
pragma solidity >=0.7.0 <0.9.0;

/// @title Create Call - Allows to use the different create opcodes to deploy a contract
/// @author Richard Meissner - <richard@gnosis.io>
contract CreateCall {
    event ContractCreation(address newContract);

    function performCreate2(
        uint256 value,
        bytes memory deploymentData,
        bytes32 salt
    ) public returns (address newContract) {
        // solhint-disable-next-line no-inline-assembly
        assembly {
            newContract := create2(value, add(0x20, deploymentData), mload(deploymentData), salt)
        }
        require(newContract != address(0), "Could not deploy contract");
        emit ContractCreation(newContract);
    }

    function performCreate(uint256 value, bytes memory deploymentData) public returns (address newContract) {
        // solhint-disable-next-line no-inline-assembly
        assembly {
            newContract := create(value, add(deploymentData, 0x20), mload(deploymentData))
        }
        require(newContract != address(0), "Could not deploy contract");
        emit ContractCreation(newContract);
    }
}

```
Metadata: 
[CreateCall.json.txt](https://github.com/ethereum/sourcify/files/7513350/CreateCall.json.txt)

**Boba Mainnet:**

### CODE REVIEW

**Comment by InoMurko** [comment]
@kuzdogan do I need to attach a mainnet example too or is Rinkeby enough?

**Comment by kuzdogan** [comment]
A test contract is needed for each network, so yes we need it

**Comment by InoMurko** [comment]
Thanks @kuzdogan!
I've deployed the same contract on both networks, just to keep things simpler:
https://blockexplorer.rinkeby.boba.network/tx/0x0c6f25547c28ac58364a1d48029302a2b16ba31c11cc8089f264465813e04b27/internal-transactions

[1b087c10e1c4f94fee8cd22752cf3b8d.json.txt](https://github.com/ethereum/sourcify/files/7529578/1b087c10e1c4f94fee8cd22752cf3b8d.json.txt)
[Storage.json.txt](https://github.com/ethereum/sourcify/files/7529579/Storage.json.txt)


https://blockexplorer.boba.network/tx/0xbfd3e063eabfaf13726da950947b659a2c4cdcd37f6f0f467c50de61061ee85f/internal-transactions

[1b087c10e1c4f94fee8cd22752cf3b8d.json.txt](https://github.com/ethereum/sourcify/files/7529573/1b087c10e1c4f94fee8cd22752cf3b8d.json.txt)
[Storage.json.txt](https://github.com/ethereum/sourcify/files/7529574/Storage.json.txt)


Source
[Storage.sol.txt](https://github.com/ethereum/sourcify/files/7529583/Storage.sol.txt)

**Comment by InoMurko** [comment]
@kuzdogan hey, is there something else I can do?

**Comment by kuzdogan** [comment]
Will look into it this week :+1:

**Comment by kuzdogan** [comment]
Looks good. Merged in https://github.com/ethereum/sourcify/pull/594

**Comment by kuzdogan** [comment]
Turning off support for Rinkeby testnet as it seems to be shut down. Also we'll be longer be actively monitoring mainnet for new contracts but continue verification support

**Pull request merged**
