### PR TITLE
kekpoint: Add KEK main net Kekistan chain ID 420420

### PR DESCRIPTION
**Pull request by ethgr0wth**
Hi-yah, Kekistan now online main net.

Name: Kekchain
Symbol: KEK
Chain ID: 420420
Network ID: 103090
RPC: https://mainnet.kekchain.com
Alternate RPC: https://rpc2.kekchain.com
Explorer: https://mainnet-explorer.kekchain.com

### CODE REVIEW

**Comment by kuzdogan** [comment]
I see the tests are failing. Please fix the tests to be able to merge

**Comment by billaure-crystaleum** [comment]
We see we are still in limbo pending merges on the followingPR's.

https://github.com/ethereum-lists/chains/pull/1626
https://github.com/DefiLlama/chainlist/pull/140

Once we get those in I will bump this thread.

**Comment by shopglobal** [comment]
Pending merge [ethereum-lists/chains](https://github.com/ethereum-lists/chains/pull/1626)

**Comment by shopglobal** [comment]
Bump

**Comment by shopglobal** [comment]
I think we need to trigger tests again since 420420 just got merged in ethereum-lists/chains

**Comment by marcocastignoli** [comment]
Can you rebase this on staging / merge from staging? I tried myself but I think you have some options that doens't allow me to push on this PR

**Comment by marcocastignoli** [comment]
Rerun the tests and succeded, probably the IPFS gateway was down

**Pull request merged**
