### PR TITLE
Add chain 7672

### PR DESCRIPTION
**Pull request by aidan-starke**
Add chain 7672 - The Root Network Porcini (Testnet)

### CODE REVIEW

**Comment by marcocastignoli** [comment]
hi @aidan-starke, thanks for the contribution. Please follow the steps here https://docs.sourcify.dev/docs/chain-support/

In particular step 1.

> Make sure the new chain is listed in [chains.json](https://github.com/ethereum/sourcify/blob/staging/src/chains.json) but this file should not be edited. It is kept in sync with [chainid.network](https://chainid.network/chains.json) (github: [ethereum-lists/chains](https://github.com/ethereum-lists/chains)) periodically. If your chain is not included, please first add your chains to the [ethereum-lists/chains](https://github.com/ethereum-lists/chains) repository first. The RPC node [should be an archive node](https://docs.sourcify.dev/docs/immutables/).

Thanks 🙂

**Comment by aidan-starke** [comment]
Hi @marcocastignoli I updated the chains using the `update-chains` script as our networks are in `ethereum-lists/chains` but not in yours.

I have reverted that commit now

**Comment by marcocastignoli** [comment]
Can you investigate why ci test "test-new-chain" is failing? thanks 🙏

**Comment by aidan-starke** [comment]
@marcocastignoli the error message is `Chain 7672 not supported!` which I believe is due to `chains.json` not being in sync with `ethereum-lists/chains`

**Comment by kuzdogan** [comment]
We've updated the `chains.json`. Can you merge from staging again?

**Comment by marcocastignoli** [comment]
> @marcocastignoli the error message is `Chain 7672 not supported!` which I believe is due to `chains.json` not being in sync with `ethereum-lists/chains`

Sorry, I tried to merge staging in this branch but I cannot push because of github permissions. Can you do it?

**Pull request merged**
