### PR TITLE
feat(add-chain-1116): add-chain-1116

### PR DESCRIPTION
**Pull request by leeyanbtcs**
Add New Chain 1116

### CODE REVIEW

**Comment by leeyanbtcs** [comment]
api key can generate from https://scan.coredao.org/my/api_key

**Comment by leeyanbtcs** [comment]
> I believe the blockexplorer does not support the endpoint `https://openapi.coredao.org/api?module=contract&action=getcontractcreation&contractaddresses=0x3A42a7161972e1476c3740f19cA110541F3A37c1&apikey=<API_KEY>` ?

@kuzdogan We have solved the problem
image

**Comment by kuzdogan** [comment]
That part seems to be fixed but the bytecodes are not matching. Are you sure these are the same contracts?

The onchain contract's runtime bytecode:
```
0x608060405234801561001057600080fd5b50600436106100365760003560e01c80632e64cec11461003b5780636057361d14610059575b600080fd5b610043610075565b60405161005091906100a1565b60405180910390f35b610073600480360381019061006e91906100ed565b61007e565b005b60008054905090565b8060008190555050565b6000819050919050565b61009b81610088565b82525050565b60006020820190506100b66000830184610092565b92915050565b600080fd5b6100ca81610088565b81146100d557600080fd5b50565b6000813590506100e7816100c1565b92915050565b600060208284031215610103576101026100bc565b5b6000610111848285016100d8565b9150509291505056fea26469706673582212206ed3db2af511a22cb0fcf7246ad3948782a2b28c1931c1141ca066a9e84e066f64736f6c63430008120033
```
The compiled contract's runtime bytecode:
```
0x608060405234801561001057600080fd5b50600436106100365760003560e01c80632e64cec11461003b5780636057361d14610059575b600080fd5b610043610075565b60405161005091906100d9565b60405180910390f35b610073600480360381019061006e919061009d565b61007e565b005b60008054905090565b8060008190555050565b60008135905061009781610103565b92915050565b6000602082840312156100b3576100b26100fe565b5b60006100c184828501610088565b91505092915050565b6100d3816100f4565b82525050565b60006020820190506100ee60008301846100ca565b92915050565b6000819050919050565b600080fd5b61010c816100f4565b811461011757600080fd5b5056fea2646970667358221220404e37f487a89a932dca5e77faaf6ca2de3b991f93d230604b1b8daaef64766264736f6c63430008070033
```

The diff:
image

**Comment by leeyanbtcs** [comment]
> That part seems to be fixed but the bytecodes are not matching. Are you sure these are the same contracts?
> 
> The onchain contract's runtime bytecode:
> 
> ```
> 0x608060405234801561001057600080fd5b50600436106100365760003560e01c80632e64cec11461003b5780636057361d14610059575b600080fd5b610043610075565b60405161005091906100a1565b60405180910390f35b610073600480360381019061006e91906100ed565b61007e565b005b60008054905090565b8060008190555050565b6000819050919050565b61009b81610088565b82525050565b60006020820190506100b66000830184610092565b92915050565b600080fd5b6100ca81610088565b81146100d557600080fd5b50565b6000813590506100e7816100c1565b92915050565b600060208284031215610103576101026100bc565b5b6000610111848285016100d8565b9150509291505056fea26469706673582212206ed3db2af511a22cb0fcf7246ad3948782a2b28c1931c1141ca066a9e84e066f64736f6c63430008120033
> ```
> 
> The compiled contract's runtime bytecode:
> 
> ```
> 0x608060405234801561001057600080fd5b50600436106100365760003560e01c80632e64cec11461003b5780636057361d14610059575b600080fd5b610043610075565b60405161005091906100d9565b60405180910390f35b610073600480360381019061006e919061009d565b61007e565b005b60008054905090565b8060008190555050565b60008135905061009781610103565b92915050565b6000602082840312156100b3576100b26100fe565b5b60006100c184828501610088565b91505092915050565b6100d3816100f4565b82525050565b60006020820190506100ee60008301846100ca565b92915050565b6000819050919050565b600080fd5b61010c816100f4565b811461011757600080fd5b5056fea2646970667358221220404e37f487a89a932dca5e77faaf6ca2de3b991f93d230604b1b8daaef64766264736f6c63430008070033
> ```
> 
> The diff: image

@kuzdogan

**Comment by leeyanbtcs** [comment]
> That part seems to be fixed but the bytecodes are not matching. Are you sure these are the same contracts?
> 
> The onchain contract's runtime bytecode:
> 
> ```
> 0x608060405234801561001057600080fd5b50600436106100365760003560e01c80632e64cec11461003b5780636057361d14610059575b600080fd5b610043610075565b60405161005091906100a1565b60405180910390f35b610073600480360381019061006e91906100ed565b61007e565b005b60008054905090565b8060008190555050565b6000819050919050565b61009b81610088565b82525050565b60006020820190506100b66000830184610092565b92915050565b600080fd5b6100ca81610088565b81146100d557600080fd5b50565b6000813590506100e7816100c1565b92915050565b600060208284031215610103576101026100bc565b5b6000610111848285016100d8565b9150509291505056fea26469706673582212206ed3db2af511a22cb0fcf7246ad3948782a2b28c1931c1141ca066a9e84e066f64736f6c63430008120033
> ```
> 
> The compiled contract's runtime bytecode:
> 
> ```
> 0x608060405234801561001057600080fd5b50600436106100365760003560e01c80632e64cec11461003b5780636057361d14610059575b600080fd5b610043610075565b60405161005091906100d9565b60405180910390f35b610073600480360381019061006e919061009d565b61007e565b005b60008054905090565b8060008190555050565b60008135905061009781610103565b92915050565b6000602082840312156100b3576100b26100fe565b5b60006100c184828501610088565b91505092915050565b6100d3816100f4565b82525050565b60006020820190506100ee60008301846100ca565b92915050565b6000819050919050565b600080fd5b61010c816100f4565b811461011757600080fd5b5056fea2646970667358221220404e37f487a89a932dca5e77faaf6ca2de3b991f93d230604b1b8daaef64766264736f6c63430008070033
> ```
> 
> The diff: image
@kuzdogan 
I don’t know if it’s because of the different compilation configurations between you and me.
image

**Comment by kuzdogan** [comment]
Did you deploy via one of the two methods suggested here? https://docs.sourcify.dev/docs/chain-support/

**Comment by leeyanbtcs** [comment]
> Did you deploy via one of the two methods suggested here? https://docs.sourcify.dev/docs/chain-support/

@kuzdogan hi, https://openapi.coredao.org/api?module=contract&action=getcontractcreation&contractaddresses=0xD5bB0035a178d56Abd23a39fB3666031084b2cb5&apikey=<API_KEY> ，The previously deployed contract did not pass [thirdweb.com](https://thirdweb.com/core-blockchain/0xD5bB0035a178d56Abd23a39fB3666031084b2cb5). This is the new verification [contract address](https://thirdweb.com/core-blockchain/0xD5bB0035a178d56Abd23a39fB3666031084b2cb5) at thirdweb.
image

**Comment by kuzdogan** [comment]
Please update the contract address to `0xD5bB0035a178d56Abd23a39fB3666031084b2cb5`

**Comment by leeyanbtcs** [comment]
> Did you deploy via one of the two methods suggested here? https://docs.sourcify.dev/docs/chain-support/

done，Thank you！

**Comment by kuzdogan** [comment]
Looks good. Finally, please can you resolve the conflicts? It's not possible to merge

**Comment by leeyanbtcs** [comment]
> Looks good. Finally, please can you resolve the conflicts? It's not possible to merge

resloved

**Comment by kuzdogan** [comment]
Sorry but your changes removes the existing chains from `sourcify-chains.ts`. Please only add your chain and don't modify the existing ones 
image

**Pull request closed without merging**
