### PR TITLE
add chains 1343 and 17172

### PR DESCRIPTION
**Pull request by connorch**
# Add New Chain 134, 17172

* [x] The branch is named as `add-chain-<chainId>`.
* [x] I haven't modified the `chains.json` file directly.
* [x] In `sourcify-chains.json` file
  * [x] I've set `supported: true`.
  * [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
* [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
* [ ] `test-new-chain` test in Circle CI is passing.

<sub>View in Huly <a href="https://app.huly.io/guest/w-kaanuzdogan-sourcify-65d30de0-75121c5c6c-fd615e?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWU1N2VkYzhiNmVjZDA0ZDYyZDJmMmMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2FhbnV6ZG9nYW4tc291cmNpZnktNjVkMzBkZTAtNzUxMjFjNWM2Yy1mZDYxNWUiLCJwcm9kdWN0SWQiOiIifQ.GTVqd6KUgfcyAj_vmWLYBBoSgoarK5E1bFq2xX4gaS0">HI-511</a></sub>

### CODE REVIEW

**Comment by kuzdogan** [comment]
The branch name is `add-chains` with an "s" (had to be without) but I fixed the script to accommodate both. Can you please merge or rebase staging?

**Comment by kuzdogan** [comment]
@connorch You can ignore the "node-v16" tests but in "test-new-chain" I see there are problems fetching the source files. 

Ideally there should be no IPFS fetching and the source files and metadata should be added within the tests. 

I see the multicall is similar to the previous ones in chain 333000333 so you can copy that and add it as a "partial" match in the tests. 17172 should pass with that.

However for 1343 I see the RPC is not working when I'm running it locally. I can't edit the code since I don't have the maintainer access and I guess it's not possible because it's from an org repo (not personal)

```js

  // Blitz Subnet Testnet
  verifyContract(
    "0x75239Ae18CEF18b42993f81CCc057dcD0c7467F4",
    "1343",
    "Blitz Subnet Testnet",
    "1343/",
    "partial"
  );

  // Eclipse Subnet Testnet
  verifyContract(
    "0xA21AEaBFF51B972aBFa131e18Ce54619422565A3",
    "17172",
    "Eclipse Subnet Testnet",
    "17172/",
    "partial"
  );
  ```

**Comment by connorch** [comment]
Thanks @kuzdogan, I'll get 17172 fixed.

For 1343, I'm also seeing the RPC issues.  AFAIK we host that RPC so hopefully it's something we can fix on our end - I'm investigating.  Sorry about that!

**Comment by connorch** [comment]
Update on 1343 - we're actively working to resolve that now.  Looks like one of our partners that runs nodes for 1343 failed to upgrade their nodes, so the RPC is failing due to the missing stake.  Should be resolved soon, but we'll need to hold off on this PR until then.  Sorry about that!

**Pull request closed without merging**
