### PR TITLE
Add New Chains Syndr 404, 444444

### PR DESCRIPTION
**Pull request by vyomshm**
# Add New Chain 404, 444444

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request for a speedy review.

## Checklist

- [x] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the `chains.json` file directly.
- [x] In `sourcify-chains.json` file
  - [x] I've set `supported: true`.
  - [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [x] `test-new-chain` test in Circle CI is passing.

### CODE REVIEW

**Comment by manuelwedler** [comment]
Could you remove the `package-lock.json` update from this PR? Other than that it looks fine :)

**Comment by vyomshm** [comment]
I have removed package json from commit history @manuelwedler

**Comment by manuelwedler** [comment]
You now included the changes to `chains.json` in your commit. Could you rebase your changes on latest staging and only include `sourcify-chains-default.json` and `chain-tests.js`? 

The `node-v16` CI job is expected to fail. Don't worry about that

**Comment by manuelwedler** [comment]
@vyomshm Could you please clean up this PR?

**Comment by kuzdogan** [comment]
Closing due to inactivity. Feel free to open and do the fixes

**Pull request closed without merging**
