### PR TITLE
Add Acala Mandala testnet

### PR DESCRIPTION
**Pull request by ThunderDeliverer**
Added Acala Mandala testnet to the Sourcify chains support in order to open a request for chain support.

### CODE REVIEW

**Comment by ThunderDeliverer** [comment]
I've just published booth of the smart contracts on Mandala (publishing is a step that allows non-developer accounts to interact with the smart contracts). Could one of the maintainers check if we can re-run the CI?

**Comment by kuzdogan** [comment]
I see the normal verification fail but immutables pass. Could you check if the provided contract is the correct one or maybe deploy a new one?

**Comment by kuzdogan** [comment]
Failing again and indeed I see the creation bytecodes are different:

Expected (`./sources/shared/1_Storage.json`): 
```
608060405234801561001057600080fd5b50610150806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80632e64cec11461003b5780636057361d14610059575b600080fd5b610043610075565b60405161005091906100d9565b60405180910390f35b610073600480360381019061006e919061009d565b61007e565b005b60008054905090565b8060008190555050565b60008135905061009781610103565b92915050565b6000602082840312156100b3576100b26100fe565b5b60006100c184828501610088565b91505092915050565b6100d3816100f4565b82525050565b60006020820190506100ee60008301846100ca565b92915050565b6000819050919050565b600080fd5b61010c816100f4565b811461011757600080fd5b5056fea2646970667358221220404e37f487a89a932dca5e77faaf6ca2de3b991f93d230604b1b8daaef64766264736f6c63430008070033
```

Found (in [blockexplorer](https://blockscout.mandala.acala.network/address/0x28F5550315182D8446e9BFa5eD24a7796ee6e2a1/contracts)):
```
0x608060405234801561001057600080fd5b5060c78061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80632e64cec11460375780636057361d146053575b600080fd5b603d607e565b6040518082815260200191505060405180910390f35b607c60048036036020811015606757600080fd5b81019080803590602001909291905050506087565b005b60008054905090565b806000819055505056fea2646970667358221220147f3cf30018f8f81e5d18392cb5863560a8fed3540f92860706834fa72bb1a664736f6c63430007040033
```

How are you deploying the contract? Are you using the `test/chains/deployContracts.js` file?

**Comment by kuzdogan** [comment]
Closing due to inactivity

**Pull request closed without merging**
