### PR TITLE
Add chain 432204 (Dexalot Mainnet)

### PR DESCRIPTION
**Pull request by ilkerulutas**
Contains details of Dexalot Mainnet with ChainID: 432204

### CODE REVIEW

**Comment by marcocastignoli** [comment]
Thanks for the PR, before merging:
* this file `services/core/src/chains.json` is read only, you need to create a PR here: [ethereum-lists/chains](https://github.com/ethereum-lists/chains) i.e. https://chainid.network/chains.json and wait till it is merged

**Comment by marcocastignoli** [comment]
Can you rebase on staging / merge from staging? we fixed some issues there?

**Comment by ilkerulutas** [comment]
Thanks for the feedback. I've made the required changes but after I reverted services/core/src/chains.json to original state circle ci tests are getting the following error "Chain 432204 not supported!".

The chain details are already merged to https://github.com/ethereum-lists/chains/pull/1855

**Comment by kuzdogan** [comment]
Yes I see the chain is added, but we need to update the chains.json file manually. We'll let you know once we did it and then you can rebase or merge from the staging.

**Comment by ligi** [comment]
could this solve the manual step:
https://github.com/ethereum-lists/chains/issues/1431 ?
There is currently people pushing this forward

**Comment by kuzdogan** [comment]
@ligi I can't remember exactly but dynamically fetching the chains was causing some trouble so I had dropped it.

**Comment by kuzdogan** [comment]
@ilkerulutas Updated with https://github.com/ethereum/sourcify/commit/f8391fdd47b85bdc1acab305f0fb75437586606e can you please rebase or merge from staging?

**Comment by ilkerulutas** [comment]
@kuzdogan thanks! Tests passing after rebasing. 
GitGuardian thinks changes in between has some secrets but as far as I can see it is a false positive and not related to this PR.

**Comment by kuzdogan** [comment]
@ilkerulutas Yes it's a false positive, and `node-v-16` test is expected to fail. LGTM 👍

**Pull request merged**
