### PR TITLE
Adding Syscoin Mainnet Support

### PR DESCRIPTION
**Pull request by tomatoskittles**
The Syscoin Mainnet is up and running, so we would like to add support to Sourcify.

ethereum-lists/chains has been merged: ethereum-lists/chains#644

An ERC-20 contract: https://github.com/willyko/nevm-test-token

Contract address https://explorer.syscoin.org/address/0xB2d0641fc8863514B6533b129fD744200eE17D29/transactions

The repo also contains the meta data: https://github.com/willyko/nevm-test-token/blob/addffcd5724bf6503cf0222e4480f13c227cf6a4/build/contracts/TestToken.json#L388

Please let me know if there is anything else needed.

Thank you for your time.

### CODE REVIEW

**Comment by tomatoskittles** [comment]
Hey @kuzdogan and @ogwurujohnson,

You two looked at our previous PR for adding the Syscoin testnet. I was wondering if you had time to check out this PR for adding in the Syscoinr Mainnet.

Thanks, in advance, for your time.

**Comment by kuzdogan** [comment]
We will try to look next week

**Comment by sidhujag** [comment]
@kuzdogan is there an update here?

**Comment by ogwurujohnson** [comment]
Will take a look at this today. @sidhujag

**Comment by tomatoskittles** [comment]
> Will take a look at this today. @sidhujag

Hey @ogwurujohnson just wondering if there is any update on this.

**Comment by ogwurujohnson** [comment]
@tomatoskittles please can you confirm that this test contract is deployed on the address you shared? The error i get trying to verify it states otherwise

**Comment by tomatoskittles** [comment]
> @tomatoskittles please can you confirm that this test contract is deployed on the address you shared? The error i get trying to verify it states otherwise

I've been told I did not specify the branch when sharing the contract. Please try this updated link:

An ERC-20 contract: https://github.com/ethereum/sourcify/pull/612#issuecomment-1008063962

Sorry about that!

**Comment by ogwurujohnson** [comment]
No worries! 🙂

**Comment by tomatoskittles** [comment]
Thanks @ogwurujohnson !!!

**Comment by kuzdogan** [comment]
Closing as added with #626

**Pull request closed without merging**
