### PR TITLE
Add chain 100009

### PR DESCRIPTION
**Pull request by ifavo**
# Add New Chain 100009 + 100010

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request for a speedy review.

## Checklist

- [x] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the `chains.json` file directly.
- [x] In `sourcify-chains.json` file
  - [x] I've set `supported: true`.
  - [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
  - because there is no rpc in chains.json 
- [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [x] `test-new-chain` test in Circle CI is passing.

### CODE REVIEW

**Comment by kuzdogan** [comment]
Thanks for the PR. Can you please remove the rpc fields here and instead add them to your entry in the [ethereum-lists/chains](https://github.com/ethereum-lists/chains)?

**Comment by ifavo** [comment]
@kuzdogan I aj

> Thanks for the PR. Can you please remove the rpc fields here and instead add them to your entry in the [ethereum-lists/chains](https://github.com/ethereum-lists/chains)?

They are not in that repository because they are not official ones.

**Comment by kuzdogan** [comment]
The chain should have an RPC in https://chainid.network/chains.json (which we mirror with `chains.json` file). It's odd to have a chain without any RPCs.

We base our RPCs from the ethereum-lists/chains repo i.e. they need to appear in https://chainid.network/chains.json. After adding the RPCs to there you can ping us and we'll update the `chains.json` file. Please don't modify `chains.json` manually.

**Comment by ifavo** [comment]
I did add two PRs there:

- https://github.com/ethereum-lists/chains/pull/5285
- https://github.com/ethereum-lists/chains/pull/5286

… and removed the rpc entries from the JSON file. I'll ping you again, when the PRs have been accepted.

**Comment by ifavo** [comment]
@kuzdogan Both RPC are now in the other repo. Is there anything else blocking this PR now?

**Comment by ifavo** [comment]
@kuzdogan thanks a lot for taking the time to adjust what was needed! 🙏

**Review by kuzdogan — APPROVED** [review]
The tests run only one chain (since the branch name is missing the other chain, had to be `add-chain-100009-100010`). But I've checked locally and they pass

**Comment by ifavo** [comment]
> The tests run only one chain (since the branch name is missing the other chain, had to be `add-chain-100009-100010`). But I've checked locally and they pass

Thanks again, and I will remember this if I do another PR in the future!

**Comment by kuzdogan** [comment]
@ifavo no worries :) Just bear in mind this will go with the next release and unfortunately it will take some time since we're in the middle of an infra migration. Lmk if this is needed on your side and we'll see what we can do

**Comment by ifavo** [comment]
Do you have an estimate for that release? Something rough to have a feeling on how long it might take. No hurry on my end.

**Comment by kuzdogan** [comment]
@ifavo I'd say something around the end of the month

**Comment by ifavo** [comment]
@kuzdogan thats perfectly fine for me, months would have startled me more, I'll add a notification for the release.

**Pull request merged**
