### PR TITLE
Add chain 9996 9977(Mind Chain)

### PR DESCRIPTION
**Pull request by nnlgsakib**
# Add New Chain <chainId>

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request.

## Checklist

- [x] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the [chains.json](../../src/chains.json) file directly.
- [x] In [sourcify-chains.ts](../../src/sourcify-chains.ts) file
  - [x] I've set `supported: true`.
  - [x] I've set `monitored: false`.
  - [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [x] `test-new-chain` test in Circle CI is passing.

### CODE REVIEW

**Comment by kuzdogan** [comment]
Can you please the package-lock.json modification please?

**Comment by kuzdogan** [comment]
Sorry should be: Can you ~~please~~ remove the package-lock.json modification please?

Looks good now

**Comment by kuzdogan** [comment]
Looks like the RPCs for the testnet (9977) are not working. If not fixed we are going to need to remove support for this chain.

```bash
curl -L 'https://testnet-msc.mindchain.info/' \
-H 'Content-Type: application/json' \
-d '{
	"jsonrpc":"2.0",
	"method":"eth_getCode",
	"params":[
		"0x6720b7a5974373C3F6bdE96c09bA4ffdddEEAeD7", 
		"latest"
	],
	"id":21
}'
```

**Comment by nnlgsakib** [comment]
> Looks like the RPCs for the testnet (9977) are not working. If not fixed we are going to need to remove support for this chain.
> 
> ```shell
> curl -L 'https://testnet-msc.mindchain.info/' \
> -H 'Content-Type: application/json' \
> -d '{
> 	"jsonrpc":"2.0",
> 	"method":"eth_getCode",
> 	"params":[
> 		"0x6720b7a5974373C3F6bdE96c09bA4ffdddEEAeD7", 
> 		"latest"
> 	],
> 	"id":21
> }'
> ```

its running now

**Comment by kuzdogan** [comment]
@nnlgsakib thanks

**Comment by kuzdogan** [comment]
It's not working again in 3rd week in a row. Unfortunately we are removing support as the tests keep failing. Please stabilize the RPCs and ping us again.

**Comment by nnlgsakib** [comment]
> It's not working again in 3rd week in a row. Unfortunately we are removing support as the tests keep failing. Please stabilize the RPCs and ping us again.

OK Sir. You can remove the testnet, we are upgrading our network. It going to take a bit longer.Will ping after the upgrade . Thanks

**Pull request merged**
