### PR TITLE
Add Polygon zkEVM Cardona Testnet chain

### PR DESCRIPTION
**Pull request by marcocastignoli**
# Add New Chain 2442
Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request for a speedy review.

## Checklist

- [x] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the `chains.json` file directly.
- [x] In `sourcify-chains.json` file
  - [x] I've set `supported: true`.
  - [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [x] `test-new-chain` test in Circle CI is passing.

### CODE REVIEW

**Review by manuelwedler — APPROVED** [review]

**Review by kuzdogan — CHANGES_REQUESTED** [review]
Can you please add https://zkevm.blockscout.com/

**Comment by marcocastignoli** [comment]
> Can you please add https://zkevm.blockscout.com/

I don't think this is Cardona

**Comment by kuzdogan** [comment]
Ok yeah, but can you then check if the testnet Etherscan API needs an API key? If not let's remove it from the chains.json. Sometimes Etherscan testnet instances don't ask for API keys, we don't need to worry about API limits then.

**Comment by marcocastignoli** [comment]
On the [official website it says](https://docs.polygonscan.com/cardona-polygon-zkevm) that it uses polygon's mainnet API KEY

> An API key generated on PolygonScan can be used for both [Polygon zkEVMChain mainnet](https://zkevm.polygonscan.com/) and [testnet ](https://sepolia-zkevm.polygonscan.com/)explorers 🏗️ .

**Review by kuzdogan — APPROVED** [review]

**Pull request merged**
