### PR TITLE
Update test contract address for Arthera Testnet

### PR DESCRIPTION
**Pull request by bertux**
because of testnet reset

# Update New Chain 10243

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request for a speedy review.

## Checklist

- [x] I haven't modified the `chains.json` file directly.
- [x] In `sourcify-chains.json` file
  - [x] I've set `supported: true`.
  - [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [x] `test-new-chain` test in Circle CI is passing.

### CODE REVIEW

**Comment by bertux** [comment]
@kuzdogan do I need to change the branch name just for changing the contract address ?

**Comment by marcocastignoli** [comment]
no need for this, I can run the test locally once I merge this PR

**Comment by bertux** [comment]
> no need for this, I can run the test locally once I merge this PR

I've tried to run locally the command below as documented but it outputs an uncaught exception :
`NEW_CHAIN_ID=10243 npx mocha test/chains/chain-tests.js --exit`

```
1) Test Supported Chains
       should verify a contract on Arthera Testnet (10243):
     Uncaught Error: Configuration property "repositoryV1.path" is not defined
Response body: {"result":[{"address":"0xE115Ef16e46bbF46591170D712140eC553C43553","chainId":"10243","runtimeTransformations":[],"creationTransformations":[],"runtimeTransformationValues":{"libraries":{}},"creationTransformationValues":{"libraries":{}},"onchainRuntimeBytecode":"0x608060405234801561001057600080fd5b50600436106100365760003560e01c80632e64cec11461003b5780636057361d14610059575b600080fd5b610043610075565b60405161005091906100d9565b60405180910390f35b610073600480360381019061006e919061009d565b61007e565b005b60008054905090565b8060008190555050565b60008135905061009781610103565b92915050565b6000602082840312156100b3576100b26100fe565b5b60006100c184828501610088565b91505092915050565b6100d3816100f4565b82525050565b60006020820190506100ee60008301846100ca565b92915050565b6000819050919050565b600080fd5b61010c816100f4565b811461011757600080fd5b5056fea2646970667358221220404e37f487a89a932dca5e77faaf6ca2de3b991f93d230604b1b8daaef64766264736f6c63430008070033","libraryMap":{},"immutableReferences":{},"creatorTxHash":"0xad038e36145d6aef2e20080971244d8a595ee57ba08771b41df76c3d5ee96dd0","onchainCreationBytecode":"0x608060405234801561001057600080fd5b50610150806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80632e64cec11461003b5780636057361d14610059575b600080fd5b610043610075565b60405161005091906100d9565b60405180910390f35b610073600480360381019061006e919061009d565b61007e565b005b60008054905090565b8060008190555050565b60008135905061009781610103565b92915050565b6000602082840312156100b3576100b26100fe565b5b60006100c184828501610088565b91505092915050565b6100d3816100f4565b82525050565b60006020820190506100ee60008301846100ca565b92915050565b6000819050919050565b600080fd5b61010c816100f4565b811461011757600080fd5b5056fea2646970667358221220404e37f487a89a932dca5e77faaf6ca2de3b991f93d230604b1b8daaef64766264736f6c63430008070033","status":"perfect"}]}
```
but at the end I see `"status":"perfect"` so does it mean the verification worked ?

**Comment by bertux** [comment]
it comes from services/server/test/helpers/assertions.js calling config.get("repositoryV1.path") and repositoryV1.path is not defined in services/server/src/config/local-test.js
even after defining it in local-test.js I still have the same error.

**Comment by bertux** [comment]
replacing it by config.get("repository.path") makes the tests work :-)

**Comment by marcocastignoli** [comment]
> replacing it by config.get("repository.path") makes the tests work :-) But it's not the purpose of this PR to fix that and I'm not sure how it should be fixed because all other config files uses repositoryV1 instead of repository so I don't want to break things somewhere else.

I fixed it, thanks for the feedback 👍

**Pull request merged**
