### PR TITLE
feat(chains): add supporting to metis, fuse, aurora

### PR DESCRIPTION
**Pull request by developerfred**
## Add supporting layer2 Chains

- [Metis](https://l2beat.com/projects/metis/) ✅ 
- [Fuse](https://defillama.com/chain/Fuse)  ✅ 
- [Aurora](https://defillama.com/chain/Aurora) ✅ 

## why should i do this merge?

When the contract is verified, confidence in the chain and in the protocol increases, a contract that is verified by being audited by everyone isos generates a common sense of security. The more contracts verified, the greater the security of the chain.

### CODE REVIEW

**Comment by kuzdogan** [comment]
Can you please provide test contracts for each chain added?

**Comment by developerfred** [comment]
@harshudasi sure!

**Comment by kuzdogan** [comment]
I see 6 chains being added. Could you please add contracts for the mainnets? These are needed to make sure the verification for these networks are working.

**Comment by spilin** [comment]
@developerfred, @kuzdogan. I appreciate your time spend adding Aurora to Sourcify. 
Can i suggest adding Aurora using sperate [pr](https://github.com/ethereum/sourcify/pull/624)
This one does have required info added to `ui/src/common/constants.ts` and also aurora is already present in [chains.json](https://github.com/ethereum/sourcify/blob/master/services/core/src/chains.json) so there is no need of adding it again.

Tnx in advance

**Comment by developerfred** [comment]
Thanks @spilin, I believe your PR serves as a test to validate my application.
https://github.com/ethereum/sourcify/pull/624

**Comment by developerfred** [comment]
@kuzdogan I did the deploys on the test chain because I don't have gas on the other end of the chain.

**Comment by kuzdogan** [comment]
Closing as no contracts for 

> I see 6 chains being added. Could you please add contracts for the mainnets? These are needed to make sure the verification for these networks are working.

Closing as contracts were not provided. A contract is needed on each chain, either newly deployed or an existing contract to test verification.

Please follow the docs for chain support requests: https://docs.sourcify.dev/docs/chain-support/

**Pull request closed without merging**
