### PR TITLE
Add godwoken mainnet

### PR DESCRIPTION
**Pull request by m-bo-one**
Just added a new chains.json because the previous has already outdated.

### CODE REVIEW

**Comment by kuzdogan** [comment]
Two things: 
1. Please don't modify the chains.json manually.
1. can you rebase onto/merge from staging to get the latest changes and run the tests?

**Comment by m-bo-one** [comment]
> Two things:
> 
> 1. Please don't modify the chains.json manually.
> 2. can you rebase onto/merge from staging to get the latest changes and run the tests?

will do

**Comment by Kuzirashi** [comment]
@kuzdogan 

I have no idea sir how to modify the chains.json file and we need it to include Godwoken Mainnet which is a new chain added in July. Are you able to help us with that? 😅 Last time you created a PR updating chains.json and that was extremely helpful. Sorry for the trouble.

**Comment by kuzdogan** [comment]
@Kuzirashi Ok now I don't see `chains.json` being modified maybe I confused it or the latest commits removed that 😅 

If you can rebase onto staging or merge from staging, and the tests run it should be enough

**Comment by m-bo-one** [comment]
> @Kuzirashi Ok now I don't see `chains.json` being modified maybe I confused it or the latest commits removed that 😅
> 
> If you can rebase onto staging or merge from staging, and the tests run it should be enough

already did this

**Comment by Kuzirashi** [comment]
@kuzdogan thank you for updating chains.json!
@m-bo-one already rebased the PR to include the latest chains.json.

I tested the branch locally and tests pass:
```
NEW_CHAIN_ID=71402 npx mocha test/chains/chain-tests.js --exit
```

```
    ✓ should verify a contract on Godwoken Mainnet (71402) (2602ms)
...
    ✓ should verify a contract with immutables on Godwoken Mainnet (71402) (1048ms)
```

**Comment by kuzdogan** [comment]
Indeed it works but for some reason, the CI didn't work.

**Comment by kuzdogan** [comment]
Verification support for the network will be disabled since tests have been consistently failing https://app.circleci.com/pipelines/github/ethereum/sourcify/9023/workflows/edc01efe-d388-4625-8972-51a6e01627f3/jobs/53034

**Pull request merged**
