### PR TITLE
Add chain 48795 8227 11227 

### PR DESCRIPTION
**Pull request by nstamm10**
# Add New Chain <chainId>

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request for a speedy review.

## Checklist

- [ ] The branch is named as `add-chain-<chainId>`.
- [ ] I haven't modified the `chains.json` file directly.
- [ ] In `sourcify-chains.json` file
  - [ ] I've set `supported: true`.
  - [ ] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [ ] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [ ] `test-new-chain` test in Circle CI is passing.

### CODE REVIEW

**Review by manuelwedler — CHANGES_REQUESTED** [review]
Just checked the test for chain 11227. It seems like the hash inside the metadata.json (`0xccd3a2d98095724a5cedd2cfd540829dce3614483f860b7e4612cd5019b7ac88`) is not matching the calculated hash for the provided `Multicall3.sol` file. How did you generate the metadata.json?

**Comment by nstamm10** [comment]
Just updated the metadata with calculated metadata using the `solc` compiler, but looks like tests are still failing.

**Comment by nstamm10** [comment]
I used solc Multicall3.sol --metadata on the file and got that output. I am not sure what went wrong there, I will try with your version.

**Comment by manuelwedler** [comment]
I'm sorry, but if you use my metadata.json, you won't get a perfect match. The metadata hash will be different on-chain. You will need the exact same metadata that was generated for the actually deployed contract. You could deploy it again though.

Besides that, the test says now that there is no contract deployed at `0xD0bB2f670f8743E5eDA59C4AB746C5CC5132C7bb`.

**Comment by manuelwedler** [comment]
@nstamm10 Could you please clean up this PR? We will close it in a week if it stays inactive

**Comment by nstamm10** [comment]
Hey @manuelwedler, thanks for all the help. Unforunately, I did not deploy those contracts myself so I don't have the metadata. I will close and reopen when I have more information.

**Comment by nstamm10** [comment]
Closing

**Pull request closed without merging**
