### PR TITLE
Add Ubiq support

### PR DESCRIPTION
**Pull request by jyap808**
Updates chains.json from https://chainid.network/chains.json.

### CODE REVIEW

**Review by ligi — COMMENTED** [review]
we are currently discussing the policy for inclusion here: https://github.com/ethereum/sourcify/issues/525

**Comment by kuzdogan** [comment]
Can you provide a source code + metadata + contract address of a contract that we can test?

**Comment by jyap808** [comment]
@kuzdogan I've created and deployed this.

https://github.com/ubiq/ubiq-sourcify-sample

Thank!

**Comment by kuzdogan** [comment]
Added to staging with 79f1f44b1b663900f1d8593930d857760ec9104e

**Pull request closed without merging**
