### PR TITLE
add-chain-641230

### PR DESCRIPTION
**Pull request by BearNetwork-BRNKC**

### CODE REVIEW

**Comment by kuzdogan** [comment]
The tests are not passing. Also please don't add an `rpc` in `sourcify-chains.ts`. This should be taken from `chains.json`. 

I see you've been opening several PRs. Please make sure your tests pass locally before you submit a PR.

**Comment by BearNetwork-BRNKC** [comment]
> The tests are not passing. Also please don't add an `rpc` in `sourcify-chains.ts`. This should be taken from `chains.json`.
> 
> I see you've been opening several PRs. Please make sure your tests pass locally before you submit a PR.



Ok. I try to delete the RPC.

Locally passed verifyContract, but verifyContractWithImmutables failed, and neither of them passed after PR.

In chainlist.org, you can search for 641230 or BRNKC, but if it is sourcify chains.json, for some reason, there is no us.

**Comment by kuzdogan** [comment]
You can see it's added at https://github.com/ethereum/sourcify/blame/staging/services/core/src/chains.json#L13165-L13190

I see the error `{ error: 'None of the RPCs responded' }` in tests. Could the RPC server be blocking CircleCI requests? 

I ran the tests locally and both of the tests are failing. Are you deploying the contracts with the provided deploy scripts?

**Comment by BearNetwork-BRNKC** [comment]
Ok ,
I will try to deploy the contract using deployContracts.js









熊網區塊鏈-Bear Network-BRNKC
Web : https://bearnetwork.net
Doc : https://docs.bearnetwork.net
Linkedin : https://bit.ly/bearnetwork_net
<https://www.linkedin.com/company/bearnetwork>



Kaan Uzdoğan ***@***.***> 於 2023年2月17日 週五 下午5:10寫道：

**Comment by BearNetwork-BRNKC** [comment]
HI

I use

npx mocha test/chains/deployContracts.js --chainId=641230
--privateKey=xxxxxxxxxxxxxxxxxxxc7a0676286a853cdcf40f0xxxxxxxxx3439008edf920
--immutableValue 641230


Get  0 passing (2ms)







熊網區塊鏈-Bear Network-BRNKC
Web : https://bearnetwork.net
Doc : https://docs.bearnetwork.net
Linkedin : https://bit.ly/bearnetwork_net
<https://www.linkedin.com/company/bearnetwork>



Kaan Uzdoğan ***@***.***> 於 2023年2月17日 週五 下午5:10寫道：

**Comment by kuzdogan** [comment]
Ok you need to use those contracts deployed by the script in the tests

**Comment by BearNetwork-BRNKC** [comment]
wow , i did it.

✓ should verify a contract on Bear Network Chain Mainnet (641230) (5656ms)
✓ should verify a contract with immutables on Bear Network Chain Mainnet
(641230) (5742ms)
 2 passing (11s)










熊網區塊鏈-Bear Network-BRNKC
Web : https://bearnetwork.net
Doc : https://docs.bearnetwork.net
Linkedin : https://bit.ly/bearnetwork_net
<https://www.linkedin.com/company/bearnetwork>



Kaan Uzdoğan ***@***.***> 於 2023年2月17日 週五 下午9:55寫道：

**Comment by BearNetwork-BRNKC** [comment]
The node uses --http.corsdomain "*" , and --ws.origins "*" , normally it
should be able to accept all communications without blocking the test.











熊網區塊鏈-Bear Network-BRNKC
Web : https://bearnetwork.net
Doc : https://docs.bearnetwork.net
Linkedin : https://bit.ly/bearnetwork_net
<https://www.linkedin.com/company/bearnetwork>



Kaan Uzdoğan ***@***.***> 於 2023年2月17日 週五 下午9:55寫道：

**Comment by BearNetwork-BRNKC** [comment]
> Ok you need to use those contracts deployed by the script in the tests

I am normal locally.

Now I don't know what to do.

It seems that it can only be used in Flatten authentication

Sourcify is a great project, it's just a shame we might not be able to use it.

**Comment by kuzdogan** [comment]
As suggested above, the RPC is putting a Cloudflare check before the CircleCI requests and therefore the tests are failing. 

I recommend not putting your RPC behind this or using a different way to limit requests as this is not an expected response from a JSON RPC endpoint. Even if this works for Sourcify, this can cause unexpected behavior at different 

I manually SSH'ed the CircleCi container to see what the received response is. It is as follows:
```html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">


</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico" alt="Icon for brnkc-mainnet.bearnetwork.net"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            brnkc-mainnet.bearnetwork.net
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=79c7af701f46177d')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            brnkc-mainnet.bearnetwork.net needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/?__cf_chl_f_tk=v.E8NkQdR5w0fEPhlCT6Z7nreX1mRJ6PqNvNuZ.hF5E-1676900753-0-gaNycGzNCXs" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="un8m7nK8UUZqhm3emJ1rR.G8Qx6nzEfSlNEpAKs9KMY-1676900753-0-AUkTBGvr6S7WsFnaM_YS9K1ykcL2Wj5WencandUXXVyabCjj2LqrOiD4hXdFaoHgfUq8LVojFc5YU9iSiEd9z00kVH1dKcS8m_eu8TbxBLW-qK36xMZ2WE7ER77K4E9RwOtza5JFKTss2bMrP10BSTuQwuHS-yegAImA-PWcRJsfHHgrSCJhIVq78i4M5OjjNenxdzOvfFVEBFBaKwRS50mmjGqalomUHN1oAAfwZfyvvQOKhs3SM9LQvNAbxNYSkB2ITXponEPoP0LwPg22GmpCM_47KJmpTaZwfOeDHkWheruH_IA3mMJLWtkOp3gd_iTLv8LqWY5jm_ycUvH5nVDRAnCAJg8QHtLet4rMa4G2TKMCErJSf3Ek1tt2BFFo6aK3XVGHzOoihPDp-gkVR76_vS74M8ONGHKq1VZ0T6G9BHh3dHpbc4SnH1TEZ3QaQqS12985KResbS0Z_2V6bf7zM5enbBlyYoldMipQ4bKkfubi1a1rnNVCJ2qv7n8rdzNU4QhhT24e0MpsGg9UeMcYuzrnzYHJrL6Gxv1tRs9eDGjbO0JnUkAAFctJ4cwdaInyzJscAm2LCElwBwzQJ69vZruYAXnK1bbbTXSzQ7YRBP67mgXqcsSr58zI8BBCwUWCS5b66OFwdt6vQYDBoWQ-9u7QToaTFSC2tDoGN5X4znpqngmXN5WtsVJzeZ4glU0vxBPBqMgfhqQ4yx6gLIPKRB8Nmtun0TnGX_Zh_01mmuSmJsIdx8kPIYPWiCiR6neuhCU_p8_RQNbI8EcGYITNYd42VB5og3xQMC1rlESUarRnzS7BoUfMj4uY8LztG39woi4S6VIwXaeBynqxjt2-G5NxouYhO6_HeZ5L03GAdfd9TNRBmIbxJ8fEOcuiJ-rldkvIN2Cc7XF5gYRuX9ufbrVfRw6h4sea4hiQflNg6SowL15_srW3p32XE0ZU818hOqucFCA0rLIpB3rE6PdPEsiPfnt6KiiFCfu6j271qr266ILWw0ripnMtJxf6fLCWOtJwLLSGW6tDXDRRh036orn25AK2J0IqzolfHsTDROdwxgBA7uOP2ygoBOfqiE6drjABwtV8--4lfhIIoEsXbhIbiE4DgWsRR4s3vw2G13oPxJmv2-nsgdcwL4daZjtaYcta5cs9ucbRk24IsNa_-OkxxVCd3qNfo2VzlnS6XbE0imcDCYYhkFP9jCXtYPcFEEkbjC4VFYH6OIps0mqrpquiYFZPkrh4IdRAZvC1klgTDvdkLwaunMk0zR-6aKw9gN3qigtBOmlwOJx4Hb2uqw1P14eudl3ZLPUtvXvPVADaviTXLCQKVPxFya7IwtbvyC1QPmmm7CP1bRMOWN_KaUtXQE49eQIAMn_E0HCcsHiRlNeh9UH96ToksyqKnd2uyhRnf0Z4FVe3bvXTGJE4C2iOn-o5xlQ-M0ljrxqTKQQGqyG41WX4eGE6mDkqEo3QzVtCQ1ZvU85kO6yXboWY62LuYjJh-e1eT1eKXGcpcnHHQk9KeFQv6y8RmtFBuXRb3wZ_iYmvfzOCtUL3ckoUdpkRO00tHyvxxi9wDwOy0tLw_LC9QhgAAhNGcvoTl0PlSdvJDv7TJaljchrL5kXUA4j-NmOpszmDWfwFx4ecQArdUX7y1rPlp1pshovx-991LAo9O4vxFlR-61W1J2soa_OXUL6flCpjm3MZtyVQQ5OwizBNe6i04VbHINsmVHNNuWhKPaWlvf_jcqtzr4cxKN2vVTaDgms_DvKWZM1N51X6utyXJfGRn52hXLOSXv9D30Y5mzxcmNJ86xht_Oj5k8Tb4pCIqSJA9rcyjkoxgAAH8DonjNE4BTaNEPDxaf7vwxFPOwLPfufhmIiIRQwlvF0RaJGbU-RkBGuUFLt2B7lY8Tr7b7fKAxpG3f8uBCb0ufXekdxIhq3dzG9STFr5zCQL_66P6ymzsUP3cCiXLFuGvV2phLzpdhNEKM7XvH57AR2jTztQWtbcWbSflnfjAjAUfjXmRYCu0Y2lxpvKh_mEqfovvmOeuy7VIeAxl9CsEvxKKXZE454hOx9Q8HKCFSq6mCJrOCPodqxRzWosxQLoSqyqjmEDMRpSu_3LOVT2NPfnJPyqTRYxQdUybeXY1GSJijh5ghzjxR0e_Ye41hyffaZwThvkOFlf0HVAweTsT8KA7_QdMYn9PnPyqXp2rdJCfcOaLZFcgR6rf13iid7XbzWMuH9FS-agfKLfsj-ZUDWixZTQqpB1B6frylzGHHL0RSBq9o_VVV35Qm_KIxp4kUDdNmPOXsJHzjgOzu6LpNUhQMSHefl-J29SMVl0YqgLqDI83Opp07NR_9fWbPxosTyhRN4cuCZx0zPFqw">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cZone: 'brnkc-mainnet.bearnetwork.net',
            cType: 'managed',
            cNounce: '92706',
            cRay: '79c7af701f46177d',
            cHash: '05153a820a8304f',
            cUPMDTk: "\/?__cf_chl_tk=v.E8NkQdR5w0fEPhlCT6Z7nreX1mRJ6PqNvNuZ.hF5E-1676900753-0-gaNycGzNCXs",
            cFPWv: 'g',
            cTTimeMs: '1000',
            cMTimeMs: '0',
            cTplV: 4,
            cTplB: 'cf',
            cRq: {
                ru: 'aHR0cHM6Ly9icm5rYy1tYWlubmV0LmJlYXJuZXR3b3JrLm5ldC8=',
                ra: 'Y3VybC83LjY4LjA=',
                rm: 'UE9TVA==',
                d: 'Om2/bHlsujY/T9NBqKt3taQf7Ix+Fg0XNMCpentoSiBDL+yc/UpYaSEgeqxQweWMX4n/+OaExjGbhVncUEL53ulPeGUPP2hNMTMvxPfI/NrJEaUhtdtlHlHxqfPo2gXbUJYBCOIu3wh0t/gTwh4FAJ9YujzvSTXVNfGYIJ2hZCzm3iCCeHSdpqAD8edZs44dFvmX3fd3ryagbuSeqHLNYyO8xjJ9phIXA8ggMMyjTOB5OKoQwlGTaUvds0OakVaWn+uq0k/Pnfbeud41q4x3yaSWsx4WqlRj175GaoXD+ax0VxCKtibssdb/2gAh4EbUxWeVteAXAc6x1SY3SgjtiJfD5cO8lTeWzG3uwaKCnA8r5YgWb7XaSYzg1VlNKw/U4wJiBlQWce1203C3sB9+euuLjlM/Zl2ylp+PDcEtennIIAZPKhH8/55O+k8y4SsGY6cAxhZZ+47ROaFoFAgLqr9I/DyWRW8Ybzh4ulCikJa578ojq0Xi4PhPJ/ei45x2KoeCPmH/Pb5Z8qrMX3icbpRl5fdVJk4sn+eEIQLdAqOTiDZJCMDb4YxBCs2bG6UwS4GqMaPmqkBTm9Ug3ZP9QQfPFLF0B2UakrVvuTOlllVurzU9Z0IWrq5FTSIGTUMpgNSaQ5dhcZNy1nGRc4+SKgFkT+6T5E+EQ6k2Qixa0AK6wz+KlPaJpWuEBGw/olVt',
                t: 'MTY3NjkwMDc1My45MzgwMDA=',
                m: '7elgtcUs7APLrBrznQCq11IPKLwTNJxqU9wxxxQAf/Q=',
                i1: 'Vx4KXXwCYuZXGZwOgFNpaQ==',
                i2: 'xDCEErEwufFDwLKWl5rwHg==',
                zh: 'wNKj30XecE/OeQLQSETdoG+l1HjqbUbUTlrxvgp/Ud8=',
                uh: 'LgBfwTjckPmPFLl2OGGaoWOKkjIgTojK2wwoWSzqSQw=',
                hh: '2yDGrAxkuy9PZ3aVDOF8mg8eCw+ZXAr3/WBYjNWNIrk=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=79c7af701f46177d');
        trkjs.setAttribute('alt', '');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/managed/v1?ray=79c7af701f46177d';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/?__cf_chl_rt_tk=v.E8NkQdR5w0fEPhlCT6Z7nreX1mRJ6PqNvNuZ.hF5E-1676900753-0-gaNycGzNCXs" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>


    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>79c7af701f46177d</code></div>
            </div>
            <div class="text-center" id="footer-text">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=m" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>
```

I cannot guarantee it Sourcify will work with these settings and the test results for the chain in [Supported Chains](https://docs.sourcify.dev/docs/chains/) will be shown failed.

**Comment by kuzdogan** [comment]
Added the chain manually https://github.com/ethereum/sourcify/pull/934

**Comment by kuzdogan** [comment]
Hello

The chain tests have been failing. I see that te RPCs are not working. Please have a look and fix the RPC and the tests. Otherwise we'll turn off support

https://app.circleci.com/pipelines/github/ethereum/sourcify/4238/workflows/fe3a7eb0-671b-4501-96ea-b2b25532f657/jobs/23355

**Comment by BearNetwork-BRNKC** [comment]
!!!!!!!!!!!!!!!!!!!

**Pull request closed without merging**
