### PR TITLE
Add chain 295 (Hedera Mainnet)

### PR DESCRIPTION
**Pull request by svienot**
Adds support for chain 295 - Hedera mainnet

### CODE REVIEW

**Comment by marcocastignoli** [comment]
Hey @svienot, first of all thanks for the contribution! 🙏 

I see you added new sources for the tests. Existing contracts sources didn't work for some reason? Just for context, I see you followed point _5.ii_ in [Sourcify's documentation](https://docs.sourcify.dev/docs/chain-support/), my question is: why points _5.i.a_ or _5.i.b_ or _5.i.c_  didn't work for you?


Same question also for https://github.com/ethereum/sourcify/pull/1008

**Comment by svienot** [comment]
Hey @marcocastignoli!
I assumed the other methods for deploying the contracts required my having an Ethereum account at hand, which I don't. 
So I thought the easiest would just be to deploy them from one of my Hedera accounts with the Hedera SDK.

Regarding https://github.com/ethereum/sourcify/pull/1008 I think I will actually need to close it, unless you can confirm there is a way to reset repository data for a test chain?

**Comment by marcocastignoli** [comment]
> peer typescript@">=5.0.4" from abitype@0.8.2

In theory I fixed this problem, try to delete all node_modules (at least the main one and the one in `packages/lib-sourcify`). The execute in root of the project:
- `npm install`
- `npx lerna bootstrap`

**Comment by svienot** [comment]
`deployContracts` wants a 32 bytes long private key while my Hedera account private key is 48 bytes long.

**Comment by svienot** [comment]
I see that _Hedera Mainnet_ is still not listed in the available chains on the repository UI page:
https://repo.staging.sourcify.dev/select-contract/
Is it a bug or is there a distinct code change needed for that ?

**Comment by kuzdogan** [comment]
We just did a release. You should see it now

**Comment by svienot** [comment]
I was just wondering... are you aware of any test chains integrated with Sourcify which have the need to regularly reset their data? How do they deal with their verification data ?

**Comment by svienot** [comment]
I also noticed that Hedera Mainnet is listed with missing verification tests in the docs. We now have 2 tests based on the shared contracts so shouldn't these be ticked ?
Screenshot 2023-05-10 at 10 22 15

**Comment by kuzdogan** [comment]
>  I was just wondering... are you aware of any test chains integrated with Sourcify which have the need to regularly reset their data? How do they deal with their verification data ?

Not that I know of. I don't know any chains that do this or if it is considered common practice. Usually, testnets are not reset but rotated with new ones, old ones being deprecated.

> I also noticed that Hedera Mainnet is listed with missing verification tests in the docs. We now have 2 tests based on the shared contracts so shouldn't these be ticked ?

This is because the tests run weekly and Hedera tests haven't run yet. They'll run on Monday

**Pull request merged**
