### PR TITLE
Add Evmos Mainnet (9001)

### PR DESCRIPTION
**Pull request by fedekunze**

### CODE REVIEW

**Comment by kuzdogan** [comment]
Looks good!

**Comment by devli13** [comment]
@kuzdogan , any estimate on when the staging branch will be merged to main? Got a lot of folks looking forward to using sourcify to verify their contracts and want to keep them up to date

**Comment by kuzdogan** [comment]
I was going to merge early this week but needed a quick fix to staging. I'll be waiting a little more for that to make sure it's stable. So likely in 7 days I'd say

**Comment by devli13** [comment]
Alright, thanks for the update @kuzdogan

**Pull request merged**
